# Generated by Django 5.1.4 on 2025-08-10 18:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facturacion', '0001_initial'),
        ('proveedores', '0009_proveedor_agente_retencion_proveedor_retencion_renta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('total_ingresos', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_gastos', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('balance_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='CuentaPorCobrar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_creacion', models.DateField(default=django.utils.timezone.now)),
                ('fecha_caducidad', models.DateField()),
                ('estatus', models.CharField(choices=[('cobrada', 'Cobrada'), ('por_cobrar', 'Por cobrar')], max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas_por_cobrar', to='facturacion.factura')),
            ],
            options={
                'verbose_name': 'Cuenta por Cobrar',
                'verbose_name_plural': 'Cuentas por Cobrar',
            },
        ),
        migrations.CreateModel(
            name='CuentaPorPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_creacion', models.DateField(default=django.utils.timezone.now)),
                ('fecha_vencimiento', models.DateField()),
                ('estatus', models.CharField(choices=[('pagada', 'Pagada'), ('pendiente', 'Pendiente')], max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas_por_pagar', to='proveedores.proveedor')),
            ],
            options={
                'verbose_name': 'Cuenta por pagar',
                'verbose_name_plural': 'Cuentas por pagar',
            },
        ),
        migrations.CreateModel(
            name='AsientoContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField()),
                ('relacionado_con_pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finanzas.cuentaporpagar')),
            ],
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingresos', to='finanzas.presupuesto')),
            ],
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='finanzas.presupuesto')),
            ],
        ),
    ]
