# Generated by Django 5.1.4 on 2025-02-07 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=255)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('consideraciones', models.CharField(max_length=255)),
                ('estatus', models.CharField(choices=[('pendiente', 'Pendiente'), ('proceso', 'En proceso'), ('terminado', 'Terminado')], default='pendiente', max_length=20)),
            ],
        ),
    ]
