# Generated by Django 5.1.4 on 2025-04-14 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0002_producto_preciounitario'),
        ('proveedores', '0002_remove_proveedor_correo_remove_proveedor_creado_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=100)),
                ('cantidad', models.PositiveIntegerField()),
                ('fecha_ingreso', models.DateField()),
                ('fecha_salida', models.DateField(blank=True, null=True)),
                ('consideraciones', models.TextField(blank=True, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proveedores.proveedor')),
            ],
        ),
    ]
