# Generated by Django 5.1.4 on 2025-12-29 20:59

import django.db.models.deletion
import inventario.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=100)),
                ('cantidad', models.PositiveIntegerField()),
                ('ubicacion', models.CharField(default='Bodega Principal', max_length=1000)),
                ('fecha_ingreso', models.DateField()),
                ('fecha_salida', models.DateField(blank=True, null=True)),
                ('consideraciones', models.TextField(blank=True, null=True)),
                ('stock_minimo', models.PositiveIntegerField(default=0)),
                ('imagen_inventario', models.ImageField(blank=True, null=True, upload_to=inventario.models.ruta_imagen_inventario)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proveedores.proveedor')),
            ],
        ),
    ]
