# Generated by Django 5.1.4 on 2025-09-12 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='stock_minimo',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
