# Generated by Django 5.1.4 on 2026-01-23 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='ubicacion',
            field=models.TextField(default='Bodega Principal', max_length=1000),
        ),
    ]
