# Generated by Django 5.1.4 on 2025-11-27 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_inventario_stock_minimo'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='ubicación',
            field=models.CharField(default='Bodega Principal', max_length=200),
        ),
    ]
