# Generated by Django 5.1.4 on 2026-02-27 00:02

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_inventario_ubicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='categoria',
            field=core.fields.RichTextMediumField(max_length=100),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='consideraciones',
            field=core.fields.RichTextMediumField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='ubicacion',
            field=core.fields.RichTextMediumField(default='Bodega Principal', max_length=1000),
        ),
    ]
