# Generated by Django 5.1.4 on 2025-12-01 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_inventario_ubicación'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventario',
            old_name='ubicación',
            new_name='ubicacion',
        ),
    ]
