# Generated by Django 5.1.4 on 2025-12-28 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_rename_ubicación_inventario_ubicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='ubicacion',
            field=models.CharField(default='Bodega Principal', max_length=1000),
        ),
    ]
