# Generated by Django 5.1.4 on 2025-12-29 06:38

import inventario.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_alter_inventario_ubicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='imagen_inventario',
            field=models.ImageField(blank=True, null=True, upload_to=inventario.models.ruta_imagen_inventario),
        ),
    ]
