# Generated by Django 5.1.4 on 2025-12-29 20:59

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actividades', '0001_initial'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.CharField(default='equipo de uso en empresa', max_length=100)),
                ('marca', models.CharField(default='Generico', max_length=100)),
                ('modelo', models.CharField(default='Modelo Generico', max_length=100)),
                ('serie', models.CharField(default='Serie Generica', max_length=100)),
                ('codigo_interno', models.CharField(default='Codigo Interno segun SG', max_length=100)),
                ('ubicacion', models.CharField(default='Ubicación del equipo segun el cliente', max_length=100)),
                ('estatus', models.CharField(default='funcionando', max_length=50)),
                ('categoria', models.CharField(default='General', max_length=100)),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_mant', models.DateField(default=datetime.date.today, verbose_name='Fecha de Mantenimiento')),
                ('proximo_mant', models.DateField(default=datetime.date.today, verbose_name='Fecha estimada de Proximo Mantenimiento')),
                ('notas', models.TextField(blank=True)),
                ('equipo_cliente', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='historial_mantenimientos', to='equipos_clientes.equipocliente')),
                ('ordenes_trabajo', models.ManyToManyField(related_name='historial_mantenimientos', to='actividades.ordendetrabajo')),
            ],
        ),
    ]
