# Generated by Django 5.1.4 on 2026-01-23 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos_clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipocliente',
            name='ubicacion',
            field=models.TextField(default='Ubicación del equipo segun el cliente', max_length=100),
        ),
    ]
