# Generated by Django 5.1.4 on 2026-02-27 00:02

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipos_clientes', '0002_alter_equipocliente_ubicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipocliente',
            name='categoria',
            field=core.fields.RichTextSimpleField(default='General', max_length=100),
        ),
        migrations.AlterField(
            model_name='equipocliente',
            name='descripcion',
            field=core.fields.RichTextSimpleField(default='equipo de uso en empresa', max_length=100),
        ),
        migrations.AlterField(
            model_name='equipocliente',
            name='estatus',
            field=core.fields.RichTextSimpleField(default='funcionando', max_length=50),
        ),
        migrations.AlterField(
            model_name='equipocliente',
            name='marca',
            field=core.fields.RichTextSimpleField(default='Generico', max_length=100),
        ),
        migrations.AlterField(
            model_name='equipocliente',
            name='modelo',
            field=core.fields.RichTextSimpleField(default='Modelo Generico', max_length=100),
        ),
        migrations.AlterField(
            model_name='equipocliente',
            name='serie',
            field=core.fields.RichTextSimpleField(default='Serie Generica', max_length=100),
        ),
        migrations.AlterField(
            model_name='equipocliente',
            name='ubicacion',
            field=core.fields.RichTextSimpleField(default='Ubicación del equipo segun el cliente', max_length=100),
        ),
    ]
