# Generated by Django 5.1.4 on 2025-04-23 00:28

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0007_trabajo_notas'),
        ('equipos_clientes', '0002_remove_historialmantenimiento_equipo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historialmantenimiento',
            name='costo_mano_obra',
        ),
        migrations.RemoveField(
            model_name='historialmantenimiento',
            name='proveedor_mantenimiento',
        ),
        migrations.RemoveField(
            model_name='historialmantenimiento',
            name='proveedor_repuestos',
        ),
        migrations.AddField(
            model_name='historialmantenimiento',
            name='orden_trabajo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='historial_mantenimientos', to='actividades.trabajo'),
        ),
        migrations.AlterField(
            model_name='historialmantenimiento',
            name='fecha_mant',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha de Mantenimiento'),
        ),
        migrations.AlterField(
            model_name='historialmantenimiento',
            name='proximo_mant',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha estimada de Proximo Mantenimiento'),
        ),
    ]
