# Generated by Django 5.1.4 on 2026-03-27 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos_clientes', '0003_alter_equipocliente_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipocliente',
            name='categoria',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AlterField(
            model_name='equipocliente',
            name='estatus',
            field=models.CharField(default='funcionando', max_length=50),
        ),
        migrations.AlterField(
            model_name='equipocliente',
            name='marca',
            field=models.CharField(default='Generico', max_length=100),
        ),
        migrations.AlterField(
            model_name='equipocliente',
            name='modelo',
            field=models.CharField(default='Modelo Generico', max_length=100),
        ),
        migrations.AlterField(
            model_name='equipocliente',
            name='serie',
            field=models.CharField(default='Serie Generica', max_length=100),
        ),
    ]
