# Generated by Django 5.1.4 on 2025-04-23 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipos_clientes', '0003_remove_historialmantenimiento_costo_mano_obra_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historialmantenimiento',
            name='descripcion_mant',
        ),
        migrations.RemoveField(
            model_name='historialmantenimiento',
            name='mot_mant',
        ),
        migrations.RemoveField(
            model_name='historialmantenimiento',
            name='repuestos',
        ),
        migrations.RemoveField(
            model_name='historialmantenimiento',
            name='tiempo_falla',
        ),
        migrations.RemoveField(
            model_name='historialmantenimiento',
            name='tiempo_reparacion',
        ),
    ]
