# Generated by Django 5.1.4 on 2025-04-23 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0007_trabajo_notas'),
        ('equipos_clientes', '0004_remove_historialmantenimiento_descripcion_mant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historialmantenimiento',
            name='orden_trabajo',
        ),
        migrations.AddField(
            model_name='historialmantenimiento',
            name='orden_trabajo',
            field=models.ManyToManyField(related_name='historial_mantenimientos', to='actividades.trabajo'),
        ),
    ]
