# Generated by Django 5.1.4 on 2025-04-23 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipos_clientes', '0005_remove_historialmantenimiento_orden_trabajo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historialmantenimiento',
            old_name='orden_trabajo',
            new_name='ordenes_trabajo',
        ),
    ]
