# Generated by Django 5.1.4 on 2025-10-12 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos_clientes', '0006_rename_orden_trabajo_historialmantenimiento_ordenes_trabajo'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipocliente',
            name='codigo_interno',
            field=models.CharField(default='Codigo Interno segun SG', max_length=100),
        ),
    ]
