# Generated by Django 5.1.4 on 2025-11-27 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos_clientes', '0007_equipocliente_codigo_interno'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipocliente',
            name='ubicación',
            field=models.CharField(default='Ubicación del equipo segun el cliente', max_length=100),
        ),
    ]
