# Generated by Django 5.1.4 on 2025-12-01 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipos_clientes', '0008_equipocliente_ubicación'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historialmantenimiento',
            name='usuario_asignado',
        ),
    ]
