# Generated by Django 5.1.4 on 2025-12-01 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipos_clientes', '0009_remove_historialmantenimiento_usuario_asignado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipocliente',
            old_name='ubicación',
            new_name='ubicacion',
        ),
    ]
