# Generated by Django 5.1.4 on 2025-06-13 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0002_notificacion_usuario_destino'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='modulo_enlace',
            field=models.URLField(default='https://seinsv.com/admin/', max_length=500),
        ),
    ]
