# Generated by Django 5.1.4 on 2025-09-12 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0003_alter_notificacion_modulo_enlace'),
        ('productos', '0007_alter_producto_existencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.producto'),
        ),
    ]
