# Generated by Django 5.1.4 on 2025-12-29 20:59

import actividades.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ordendetrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correlativo', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Critica')], default='media', max_length=10)),
                ('tipo_actividad', models.CharField(choices=[('mantenimiento_preventivo', 'Mantenimiento Preventivo'), ('mantenimiento_correctivo', 'Mantenimiento Correctivo'), ('rutina', 'Rutina'), ('diagnostico', 'Diagnostico'), ('configuracion', 'Configuracion'), ('entrega_retiro', 'Entrega_retiro'), ('fabricacion', 'Fabricacion'), ('fontaneria', 'Fontaneria'), ('construccion', 'Construccion'), ('instalacion', 'Instalación'), ('desinstalacion', 'Desinstalación'), ('montaje', 'Montaje'), ('desmontaje', 'Desmontaje'), ('reparacion', 'Reparación'), ('otro', 'Otro')], default='mantenimiento_correctivo', max_length=30)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('estatus', models.CharField(choices=[('pendiente', 'Pendiente'), ('programado', 'Programado'), ('en_proceso', 'En Proceso'), ('terminado', 'Terminado')], default='pendiente', max_length=20)),
                ('horas_hombre_estimadas', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, null=True)),
                ('equipo_funcionando', models.CharField(choices=[('Si', 'Sí'), ('No', 'No')], default='No', max_length=4)),
                ('horarios_actividad', models.CharField(choices=[('AM', 'Matutino 6-3'), ('PM', 'Vespertino 12-9'), ('PM2', 'Nocturno 9-6'), ('8-5', 'Horario Normal 8-5')], default='8-5', max_length=4)),
                ('notas', models.TextField(blank=True)),
                ('comentarios', models.TextField(blank=True)),
                ('imagen_antes_1', models.ImageField(blank=True, null=True, upload_to=actividades.models.ruta_imagen_antes)),
                ('imagen_antes_2', models.ImageField(blank=True, null=True, upload_to=actividades.models.ruta_imagen_antes)),
                ('imagen_despues_1', models.ImageField(blank=True, null=True, upload_to=actividades.models.ruta_imagen_despues)),
                ('imagen_despues_2', models.ImageField(blank=True, null=True, upload_to=actividades.models.ruta_imagen_despues)),
                ('nombre_recibe', models.CharField(blank=True, max_length=200, null=True)),
                ('firma_cliente', models.TextField(blank=True, null=True)),
                ('firma_cliente_img', models.ImageField(blank=True, null=True, upload_to=actividades.models.firma_upload_path)),
            ],
            options={
                'verbose_name': 'Orden de trabajo',
                'verbose_name_plural': 'Órdenes de trabajo',
            },
        ),
    ]
