# Generated by Django 5.1.4 on 2025-02-07 03:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0001_initial'),
        ('clientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Proyecto',
            new_name='actividades',
        ),
    ]
