# Generated by Django 5.1.4 on 2025-12-29 20:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actividades', '0001_initial'),
        ('clientes', '0001_initial'),
        ('cotizaciones', '0001_initial'),
        ('documentacion', '0001_initial'),
        ('equipos', '0001_initial'),
        ('planes_mantenimiento', '0001_initial'),
        ('proveedores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ordendetrabajo',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='ordendetrabajo',
            name='cotizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotizaciones.cotizacion'),
        ),
        migrations.AddField(
            model_name='ordendetrabajo',
            name='detalleplan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ots_generadas', to='planes_mantenimiento.detalleplanmantenimiento'),
        ),
        migrations.AddField(
            model_name='ordendetrabajo',
            name='documentos_necesarios',
            field=models.ManyToManyField(blank=True, to='documentacion.documentacion'),
        ),
        migrations.AddField(
            model_name='ordendetrabajo',
            name='equipo',
            field=models.ManyToManyField(blank=True, to='equipos.equipo'),
        ),
        migrations.AddField(
            model_name='ordendetrabajo',
            name='herramientas_necesarias',
            field=models.ManyToManyField(blank=True, to='equipos.herramienta'),
        ),
        migrations.AddField(
            model_name='ordendetrabajo',
            name='personal_asignado',
            field=models.ManyToManyField(blank=True, related_name='trabajos_asignados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordendetrabajo',
            name='proveedores',
            field=models.ManyToManyField(blank=True, to='proveedores.proveedor'),
        ),
    ]
