# Generated by Django 5.1.4 on 2025-04-15 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0002_rename_proyecto_actividades'),
        ('cotizaciones', '0002_detallecotizacionproductos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividades',
            name='cotizacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cotizaciones.cotizacion'),
        ),
    ]
