# Generated by Django 5.1.4 on 2026-02-26 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordendetrabajo',
            name='tipo_actividad',
            field=models.CharField(choices=[('mantenimiento_preventivo', 'Mantenimiento Preventivo'), ('mantenimiento_correctivo', 'Mantenimiento Correctivo'), ('rutina', 'Rutina'), ('diagnostico', 'Diagnostico'), ('configuracion', 'Configuracion'), ('entrega_retiro', 'Entrega_retiro'), ('fabricacion', 'Fabricacion'), ('fontaneria', 'Fontaneria'), ('limpieza', 'Limpieza'), ('operacion', 'Operacion'), ('proyecto', 'Proyecto'), ('cambio', 'Cambio'), ('construccion', 'Construccion'), ('instalacion/desinstalacion electrica', 'Instalación/Desinstalación electrica'), ('montaje/desmontaje mecanico', 'Montaje/Desmontaje mecanico'), ('reemplazo', 'Reemplazo'), ('reparacion', 'Reparación'), ('varios', 'Varios'), ('otro', 'Otro')], default='mantenimiento_correctivo', max_length=50),
        ),
    ]
