# Generated by Django 5.1.4 on 2026-02-27 00:02

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0003_alter_ordendetrabajo_tipo_actividad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordendetrabajo',
            name='comentarios',
            field=core.fields.RichTextMediumField(blank=True),
        ),
        migrations.AlterField(
            model_name='ordendetrabajo',
            name='descripcion',
            field=core.fields.RichTextMediumField(blank=True),
        ),
        migrations.AlterField(
            model_name='ordendetrabajo',
            name='notas',
            field=core.fields.RichTextMediumField(blank=True),
        ),
    ]
