# Generated by Django 5.1.4 on 2025-04-15 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0003_actividades_cotizacion'),
        ('cotizaciones', '0002_detallecotizacionproductos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividades',
            name='cotizacion',
        ),
        migrations.AddField(
            model_name='actividades',
            name='cotizacion',
            field=models.ManyToManyField(to='cotizaciones.cotizacion'),
        ),
    ]
