# Generated by Django 5.1.4 on 2025-04-15 20:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0004_remove_actividades_cotizacion_actividades_cotizacion'),
        ('clientes', '0002_cliente_correo'),
        ('cotizaciones', '0002_detallecotizacionproductos_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='actividades',
            new_name='trabajo',
        ),
    ]
