# Generated by Django 5.1.4 on 2026-03-20 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0004_alter_ordendetrabajo_comentarios_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordendetrabajo',
            name='tipo_actividad',
            field=models.CharField(choices=[('mantenimiento_preventivo', 'Mantenimiento Preventivo'), ('mantenimiento_correctivo', 'Mantenimiento Correctivo'), ('rutina', 'Rutina'), ('diagnostico', 'Diagnostico'), ('configuracion', 'Configuracion'), ('entrega_retiro', 'Entrega_retiro'), ('fabricacion', 'Fabricacion'), ('fontaneria', 'Fontaneria'), ('construccion', 'Construccion'), ('instalacion', 'Instalación'), ('desinstalacion', 'Desinstalación'), ('montaje', 'Montaje'), ('desmontaje', 'Desmontaje'), ('reparacion', 'Reparación'), ('otro', 'Otro')], default='mantenimiento_correctivo', max_length=50),
        ),
    ]
