# Generated by Django 5.1.4 on 2025-04-20 06:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0005_rename_actividades_trabajo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabajo',
            name='personal_asignado',
        ),
        migrations.AddField(
            model_name='trabajo',
            name='personal_asignado',
            field=models.ManyToManyField(blank=True, related_name='trabajos_asignados', to=settings.AUTH_USER_MODEL),
        ),
    ]
