# Generated by Django 5.1.4 on 2025-04-22 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0006_remove_trabajo_personal_asignado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajo',
            name='notas',
            field=models.TextField(blank=True),
        ),
    ]
