# Generated by Django 5.1.4 on 2025-05-07 01:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0007_trabajo_notas'),
        ('clientes', '0003_seguimiento'),
        ('cotizaciones', '0003_alter_cotizacion_options_and_more'),
        ('equipos_clientes', '0006_rename_orden_trabajo_historialmantenimiento_ordenes_trabajo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='trabajo',
            new_name='Ordendetrabajo',
        ),
    ]
