# Generated by Django 5.1.4 on 2025-05-07 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0008_rename_trabajo_ordendetrabajo'),
        ('activos', '0001_initial'),
        ('documentacion', '0003_alter_documentacion_options'),
        ('proveedores', '0005_remove_proveedor_contacto_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordendetrabajo',
            options={'verbose_name': 'Orden de trabajo', 'verbose_name_plural': 'Órdenes de trabajo'},
        ),
        migrations.AddField(
            model_name='ordendetrabajo',
            name='documentos_necesarios',
            field=models.ManyToManyField(blank=True, to='documentacion.documentacion'),
        ),
        migrations.AddField(
            model_name='ordendetrabajo',
            name='equipo_funcionando',
            field=models.CharField(choices=[('Si', 'Sí'), ('No', 'No')], default='No', max_length=4),
        ),
        migrations.AddField(
            model_name='ordendetrabajo',
            name='herramientas_necesarias',
            field=models.ManyToManyField(blank=True, to='activos.activo'),
        ),
        migrations.AddField(
            model_name='ordendetrabajo',
            name='horarios_actividad',
            field=models.CharField(choices=[('AM', 'Matutino'), ('PM', 'Vespertino'), ('8-5', 'Horario Normal')], default='8-5', max_length=4),
        ),
        migrations.AddField(
            model_name='ordendetrabajo',
            name='horas_estimadas',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='ordendetrabajo',
            name='proveedores',
            field=models.ManyToManyField(blank=True, to='proveedores.proveedor'),
        ),
    ]
