# Generated by Django 5.1.4 on 2025-05-07 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0009_alter_ordendetrabajo_options_and_more'),
        ('equipos', '0010_herramienta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordendetrabajo',
            name='herramientas_necesarias',
            field=models.ManyToManyField(blank=True, to='equipos.herramienta'),
        ),
    ]
