# Generated by Django 5.1.4 on 2025-06-05 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0010_alter_ordendetrabajo_herramientas_necesarias'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordendetrabajo',
            old_name='horas_estimadas',
            new_name='horas_hombre_estimadas',
        ),
    ]
