# Generated by Django 5.1.4 on 2025-06-07 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0011_rename_horas_estimadas_ordendetrabajo_horas_hombre_estimadas'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordendetrabajo',
            name='comentarios',
            field=models.TextField(blank=True),
        ),
    ]
