# Generated by Django 5.1.4 on 2025-06-08 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0012_ordendetrabajo_comentarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordendetrabajo',
            name='correlativo',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
