# Generated by Django 5.1.4 on 2025-08-14 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0013_ordendetrabajo_correlativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordendetrabajo',
            name='prioridad',
            field=models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Critica')], default='media', max_length=10),
        ),
    ]
