# Generated by Django 5.1.4 on 2025-08-29 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0014_ordendetrabajo_prioridad'),
        ('productos', '0007_alter_producto_existencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordendetrabajo',
            name='productos_necesarios',
            field=models.ManyToManyField(blank=True, to='productos.producto'),
        ),
    ]
