# Generated by Django 5.1.4 on 2025-09-01 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0015_ordendetrabajo_productos_necesarios'),
        ('equipos_clientes', '0006_rename_orden_trabajo_historialmantenimiento_ordenes_trabajo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordendetrabajo',
            name='equipo_cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipos_clientes.equipocliente'),
        ),
    ]
