# Generated by Django 5.1.4 on 2025-09-12 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0016_ordendetrabajo_equipo_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordendetrabajo',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordendetrabajo',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordendetrabajo',
            name='horas_hombre_estimadas',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, null=True),
        ),
    ]
