# Generated by Django 5.1.4 on 2025-09-12 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0017_alter_ordendetrabajo_fecha_fin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordendetrabajo',
            name='productos_necesarios',
        ),
    ]
