# Generated by Django 5.1.4 on 2025-09-12 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0018_remove_ordendetrabajo_productos_necesarios'),
        ('cotizaciones', '0024_detallecotizacionproductos_unidades_cantidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordendetrabajo',
            name='cotizacion',
        ),
        migrations.AddField(
            model_name='ordendetrabajo',
            name='cotizacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cotizaciones.cotizacion'),
        ),
    ]
