# Generated by Django 5.1.4 on 2025-09-28 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0019_remove_ordendetrabajo_cotizacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordendetrabajo',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ordendetrabajo',
            name='hora_fin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordendetrabajo',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
