# Generated by Django 5.1.4 on 2025-09-28 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0020_ordendetrabajo_descripcion_ordendetrabajo_hora_fin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordendetrabajo',
            name='horarios_actividad',
            field=models.CharField(choices=[('AM', 'Matutino'), ('PM', 'Vespertino'), ('PM2', 'Nocturno'), ('8-5', 'Horario Normal')], default='8-5', max_length=4),
        ),
    ]
