# Generated by Django 5.1.4 on 2025-10-02 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0021_alter_ordendetrabajo_horarios_actividad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordendetrabajo',
            name='horarios_actividad',
            field=models.CharField(choices=[('AM', 'Matutino 6-3'), ('PM', 'Vespertino 12-9'), ('PM2', 'Nocturno 9-6'), ('8-5', 'Horario Normal 8-5')], default='8-5', max_length=4),
        ),
    ]
