# Generated by Django 5.1.4 on 2025-10-05 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0022_alter_ordendetrabajo_horarios_actividad'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordendetrabajo',
            name='tipo_actividad',
            field=models.CharField(choices=[('mantenimiento_preventivo', 'Mantenimiento Preventivo'), ('mantenimiento_correctivo', 'Mantenimiento Correctivo'), ('rutina', 'Rutina'), ('instalacion', 'Instalación'), ('desinstalacion', 'Desinstalación'), ('montaje', 'Montaje'), ('desmontaje', 'Desmontaje'), ('reparacion', 'Reparación'), ('otro', 'Otro')], default='mantenimiento_correctivo', max_length=30),
        ),
    ]
