# Generated by Django 5.1.4 on 2025-10-12 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0023_ordendetrabajo_tipo_actividad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordendetrabajo',
            name='estatus',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('programado', 'Programado'), ('en_proceso', 'En Proceso'), ('terminado', 'Terminado')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='ordendetrabajo',
            name='tipo_actividad',
            field=models.CharField(choices=[('mantenimiento_preventivo', 'Mantenimiento Preventivo'), ('mantenimiento_correctivo', 'Mantenimiento Correctivo'), ('rutina', 'Rutina'), ('diagnostico', 'Diagnostico'), ('configuracion', 'Configuracion'), ('entrega_retiro', 'Entrega_retiro'), ('instalacion', 'Instalación'), ('desinstalacion', 'Desinstalación'), ('montaje', 'Montaje'), ('desmontaje', 'Desmontaje'), ('reparacion', 'Reparación'), ('otro', 'Otro')], default='mantenimiento_correctivo', max_length=30),
        ),
    ]
