# Generated by Django 5.1.4 on 2025-10-12 19:44

import actividades.models
import jsignature.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0024_alter_ordendetrabajo_estatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordendetrabajo',
            name='firma_cliente',
            field=jsignature.fields.JSignatureField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordendetrabajo',
            name='firma_tecnico',
            field=jsignature.fields.JSignatureField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordendetrabajo',
            name='imagen_antes_1',
            field=models.ImageField(blank=True, null=True, upload_to=actividades.models.ruta_imagen_antes),
        ),
        migrations.AddField(
            model_name='ordendetrabajo',
            name='imagen_antes_2',
            field=models.ImageField(blank=True, null=True, upload_to=actividades.models.ruta_imagen_antes),
        ),
        migrations.AddField(
            model_name='ordendetrabajo',
            name='imagen_despues_1',
            field=models.ImageField(blank=True, null=True, upload_to=actividades.models.ruta_imagen_despues),
        ),
        migrations.AddField(
            model_name='ordendetrabajo',
            name='imagen_despues_2',
            field=models.ImageField(blank=True, null=True, upload_to=actividades.models.ruta_imagen_despues),
        ),
    ]
