# Generated by Django 5.1.4 on 2025-10-12 20:20

import actividades.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0025_ordendetrabajo_firma_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordendetrabajo',
            name='firma_cliente_img',
            field=models.ImageField(blank=True, null=True, upload_to=actividades.models.firma_upload_path),
        ),
        migrations.AddField(
            model_name='ordendetrabajo',
            name='firma_tecnico_img',
            field=models.ImageField(blank=True, null=True, upload_to=actividades.models.firma_upload_path),
        ),
    ]
