# Generated by Django 5.1.4 on 2025-10-24 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0026_ordendetrabajo_firma_cliente_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordendetrabajo',
            name='nombre_cliente',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='ordendetrabajo',
            name='firma_cliente',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordendetrabajo',
            name='firma_tecnico',
            field=models.TextField(blank=True, null=True),
        ),
    ]
