# Generated by Django 5.1.4 on 2025-10-24 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0027_ordendetrabajo_nombre_cliente_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordendetrabajo',
            old_name='nombre_cliente',
            new_name='nombre_recibe',
        ),
    ]
