# Generated by Django 5.1.4 on 2025-10-24 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0028_rename_nombre_cliente_ordendetrabajo_nombre_recibe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordendetrabajo',
            name='nombre_recibe',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
