# Generated by Django 5.1.4 on 2025-11-09 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0029_alter_ordendetrabajo_nombre_recibe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordendetrabajo',
            name='firma_tecnico',
        ),
        migrations.RemoveField(
            model_name='ordendetrabajo',
            name='firma_tecnico_img',
        ),
    ]
