# Generated by Django 5.1.4 on 2025-12-11 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0031_remove_ordendetrabajo_equipo_cliente_and_more'),
        ('equipos', '0019_alter_historialtrabajos_fecha_registro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordendetrabajo',
            name='equipo',
        ),
        migrations.AddField(
            model_name='ordendetrabajo',
            name='equipo',
            field=models.ManyToManyField(blank=True, to='equipos.equipo'),
        ),
    ]
