# Generated by Django 5.1.4 on 2025-12-11 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0032_remove_ordendetrabajo_equipo_ordendetrabajo_equipo'),
        ('cotizaciones', '0029_alter_cotizacion_equipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordendetrabajo',
            name='cotizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotizaciones.cotizacion'),
        ),
    ]
