# Generated by Django 5.1.4 on 2025-12-12 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0033_alter_ordendetrabajo_cotizacion'),
        ('planes_mantenimiento', '0008_alter_planmantenimiento_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordendetrabajo',
            name='detalleplan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ots_generadas', to='planes_mantenimiento.detalleplanmantenimiento'),
        ),
    ]
