
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: siyah777

    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    env_file:
    - .env.dev 
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=SEINS-ERP.settings.dev
      - DATABASE_URL=postgres://seinsuser:seins_password@db:5432/seinsdb
    depends_on:
      - db

volumes:
  pgdata:
