# Generated by Django 5.1.4 on 2025-12-29 20:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Documentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('codigo_documento', models.CharField(blank=True, max_length=50)),
                ('descripcion', models.TextField(blank=True)),
                ('justificacion', models.TextField(blank=True)),
                ('objetivos', models.TextField(blank=True)),
                ('categoria', models.CharField(max_length=100)),
                ('insumos_necesarios', models.TextField(blank=True)),
                ('herramientas_necesarias', models.TextField(blank=True)),
                ('personal_tecnico', models.CharField(blank=True, help_text='Ej: 1 técnico mecánico, 1 electricista', max_length=255)),
                ('tiempo_estimado', models.DurationField(blank=True, help_text='Duración estimada del procedimiento', null=True)),
                ('actividades_finales', models.TextField(default='Ninguna')),
                ('referencias', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('equipos', models.ManyToManyField(blank=True, to='equipos.equipo')),
            ],
            options={
                'db_table': 'documentacion_procedimiento',
                'ordering': ['codigo_documento'],
            },
        ),
        migrations.CreateModel(
            name='ActividadFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('documentacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades_post', to='documentacion.documentacion')),
            ],
        ),
        migrations.CreateModel(
            name='PasoProcedimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField()),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='procedimientos/pasos/')),
                ('video', models.URLField(blank=True, help_text='URL de video (YouTube, Drive, etc.)', null=True)),
                ('documentacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pasos', to='documentacion.documentacion')),
            ],
            options={
                'ordering': ['orden'],
                'unique_together': {('documentacion', 'orden')},
            },
        ),
    ]
