# Generated by Django 5.1.4 on 2025-04-14 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=50)),
                ('categoria', models.CharField(max_length=100)),
                ('fecha_actualizacion', models.DateField()),
            ],
        ),
    ]
