# Generated by Django 5.1.4 on 2026-01-23 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actividadfinal',
            options={'verbose_name': 'Actividad final', 'verbose_name_plural': 'Actividades finales'},
        ),
        migrations.AlterModelOptions(
            name='documentacion',
            options={'ordering': ['codigo_documento'], 'verbose_name': 'Documentacion', 'verbose_name_plural': 'Documentaciones'},
        ),
        migrations.AlterField(
            model_name='pasoprocedimiento',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='documentacion/procedimientos/pasos/'),
        ),
    ]
