# Generated by Django 5.1.4 on 2025-04-15 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentacion',
            name='documento',
            field=models.URLField(blank=True, null=True),
        ),
    ]
