# Generated by Django 5.1.4 on 2026-03-20 04:15

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentacion', '0002_alter_actividadfinal_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentacion',
            name='actividades_finales',
            field=core.fields.RichTextMediumField(default='Ninguna'),
        ),
        migrations.AlterField(
            model_name='documentacion',
            name='categoria',
            field=core.fields.RichTextMediumField(max_length=100),
        ),
        migrations.AlterField(
            model_name='documentacion',
            name='codigo_documento',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='documentacion',
            name='herramientas_necesarias',
            field=core.fields.RichTextMediumField(blank=True),
        ),
        migrations.AlterField(
            model_name='documentacion',
            name='insumos_necesarios',
            field=core.fields.RichTextMediumField(blank=True),
        ),
        migrations.AlterField(
            model_name='documentacion',
            name='justificacion',
            field=core.fields.RichTextMediumField(blank=True),
        ),
        migrations.AlterField(
            model_name='documentacion',
            name='objetivos',
            field=core.fields.RichTextMediumField(blank=True),
        ),
        migrations.AlterField(
            model_name='documentacion',
            name='personal_tecnico',
            field=core.fields.RichTextMediumField(blank=True, help_text='Ej: 1 técnico mecánico, 1 electricista', max_length=255),
        ),
        migrations.AlterField(
            model_name='documentacion',
            name='referencias',
            field=core.fields.RichTextMediumField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentacion',
            name='titulo',
            field=models.TextField(max_length=255),
        ),
    ]
