# Generated by Django 5.1.4 on 2025-04-22 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentacion', '0002_documentacion_documento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentacion',
            options={'verbose_name': 'Documento', 'verbose_name_plural': 'Documentos'},
        ),
    ]
