# Generated by Django 5.1.4 on 2026-02-27 00:02

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentacion', '0002_alter_actividadfinal_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentacion',
            name='aprobo',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='documentacion',
            name='elaboro',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='documentacion',
            name='revision',
            field=models.CharField(default='00', max_length=10),
        ),
        migrations.AddField(
            model_name='documentacion',
            name='reviso',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='actividadfinal',
            name='descripcion',
            field=core.fields.RichTextSimpleField(),
        ),
        migrations.AlterField(
            model_name='documentacion',
            name='actividades_finales',
            field=core.fields.RichTextSimpleField(default='Ninguna'),
        ),
        migrations.AlterField(
            model_name='documentacion',
            name='categoria',
            field=core.fields.RichTextSimpleField(max_length=100),
        ),
        migrations.AlterField(
            model_name='documentacion',
            name='codigo_documento',
            field=core.fields.RichTextSimpleField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='documentacion',
            name='descripcion',
            field=core.fields.RichTextSimpleField(blank=True),
        ),
        migrations.AlterField(
            model_name='documentacion',
            name='herramientas_necesarias',
            field=core.fields.RichTextSimpleField(blank=True),
        ),
        migrations.AlterField(
            model_name='documentacion',
            name='insumos_necesarios',
            field=core.fields.RichTextSimpleField(blank=True),
        ),
        migrations.AlterField(
            model_name='documentacion',
            name='justificacion',
            field=core.fields.RichTextSimpleField(blank=True),
        ),
        migrations.AlterField(
            model_name='documentacion',
            name='objetivos',
            field=core.fields.RichTextSimpleField(blank=True),
        ),
        migrations.AlterField(
            model_name='documentacion',
            name='personal_tecnico',
            field=core.fields.RichTextSimpleField(blank=True, help_text='Ej: 1 técnico mecánico, 1 electricista', max_length=255),
        ),
        migrations.AlterField(
            model_name='documentacion',
            name='referencias',
            field=core.fields.RichTextSimpleField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentacion',
            name='titulo',
            field=core.fields.RichTextSimpleField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pasoprocedimiento',
            name='descripcion',
            field=core.fields.RichTextSimpleField(),
        ),
    ]
