# Generated by Django 5.1.4 on 2026-03-20 05:53

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentacion', '0003_alter_documentacion_actividades_finales_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividadfinal',
            name='descripcion',
            field=core.fields.RichTextMediumField(),
        ),
        migrations.AlterField(
            model_name='pasoprocedimiento',
            name='descripcion',
            field=core.fields.RichTextMediumField(),
        ),
    ]
