# Generated by Django 5.1.4 on 2026-02-27 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentacion', '0003_documentacion_aprobo_documentacion_elaboro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentacion',
            name='codigo_documento',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='documentacion',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='documentacion',
            name='titulo',
            field=models.TextField(max_length=255),
        ),
    ]
