# Generated by Django 5.1.4 on 2025-12-29 08:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentacion', '0003_alter_documentacion_options'),
        ('equipos', '0021_equipo_imagen_equipo_herramienta_imagen_herramienta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentacion',
            options={'ordering': ['codigo_documento']},
        ),
        migrations.RenameField(
            model_name='documentacion',
            old_name='nombre',
            new_name='titulo',
        ),
        migrations.RemoveField(
            model_name='documentacion',
            name='documento',
        ),
        migrations.RemoveField(
            model_name='documentacion',
            name='fecha_actualizacion',
        ),
        migrations.RemoveField(
            model_name='documentacion',
            name='version',
        ),
        migrations.AddField(
            model_name='documentacion',
            name='actividades_finales',
            field=models.TextField(default='Ninguna'),
        ),
        migrations.AddField(
            model_name='documentacion',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='documentacion',
            name='codigo_documento',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='documentacion',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentacion',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='documentacion',
            name='equipos',
            field=models.ManyToManyField(blank=True, to='equipos.equipo'),
        ),
        migrations.AddField(
            model_name='documentacion',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documentacion',
            name='herramientas_necesarias',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='documentacion',
            name='insumos_necesarios',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='documentacion',
            name='justificacion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='documentacion',
            name='objetivos',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='documentacion',
            name='personal_tecnico',
            field=models.CharField(blank=True, help_text='Ej: 1 técnico mecánico, 1 electricista', max_length=255),
        ),
        migrations.AddField(
            model_name='documentacion',
            name='referencias',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentacion',
            name='tiempo_estimado',
            field=models.DurationField(blank=True, help_text='Duración estimada del procedimiento', null=True),
        ),
        migrations.CreateModel(
            name='ActividadFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('documentacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades_post', to='documentacion.documentacion')),
            ],
        ),
        migrations.CreateModel(
            name='PasoProcedimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField()),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='procedimientos/pasos/')),
                ('video', models.URLField(blank=True, help_text='URL de video (YouTube, Drive, etc.)', null=True)),
                ('documentacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pasos', to='documentacion.documentacion')),
            ],
            options={
                'ordering': ['orden'],
                'unique_together': {('documentacion', 'orden')},
            },
        ),
    ]
