# Generated by Django 5.1.4 on 2025-12-29 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentacion', '0004_alter_documentacion_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='documentacion',
            table='documentacion_procedimiento',
        ),
    ]
