# Generated by Django 5.1.4 on 2025-04-18 02:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateField(verbose_name='Fecha de ingreso')),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo')),
                ('sueldo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Sueldo')),
                ('numero_dui', models.CharField(max_length=10, verbose_name='Número de DUI')),
                ('nit', models.CharField(max_length=17, verbose_name='NIT')),
                ('id_seguro_social', models.CharField(max_length=15, verbose_name='ID de Seguro Social')),
                ('cuenta_bancaria', models.CharField(max_length=25, verbose_name='Cuenta bancaria')),
                ('fotografia', models.ImageField(blank=True, null=True, upload_to='fotografias_empleados/', verbose_name='Fotografía')),
                ('permisos', models.TextField(blank=True, null=True, verbose_name='Permisos adicionales')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
            },
        ),
    ]
