# Generated by Django 5.1.4 on 2026-02-27 00:02

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallecompetenciausuario',
            name='competencia',
            field=core.fields.RichTextSimpleField(),
        ),
        migrations.AlterField(
            model_name='detallecompetenciausuario',
            name='descripcion',
            field=core.fields.RichTextSimpleField(),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='cargo',
            field=core.fields.RichTextSimpleField(max_length=100, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='observaciones',
            field=core.fields.RichTextSimpleField(blank=True, null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='permisos',
            field=core.fields.RichTextSimpleField(blank=True, null=True, verbose_name='Permisos adicionales'),
        ),
    ]
