# Generated by Django 5.1.4 on 2025-04-18 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0002_competenciausuario_detallecompetenciausuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallecompetenciausuario',
            name='competencia',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='CompetenciaUsuario',
        ),
    ]
