# Generated by Django 5.1.4 on 2026-05-08 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0002_alter_detallecompetenciausuario_competencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='cargo',
            field=models.CharField(max_length=100, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='permisos',
            field=models.TextField(blank=True, null=True, verbose_name='Permisos adicionales'),
        ),
    ]
