# Generated by Django 5.1.4 on 2025-04-18 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0003_alter_detallecompetenciausuario_competencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallecompetenciausuario',
            name='empleado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='competencias', to='recursos_humanos.empleado', verbose_name='Empleado'),
        ),
    ]
