# Generated by Django 5.1.4 on 2025-11-09 18:00

import recursos_humanos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0004_detallecompetenciausuario_empleado'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='firma_tecnico',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='firma_tecnico_img',
            field=models.ImageField(blank=True, null=True, upload_to=recursos_humanos.models.firma_upload_path),
        ),
    ]
