# Generated by Django 5.1.4 on 2025-04-14 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('categoria', models.CharField(max_length=100)),
                ('formula', models.TextField()),
                ('criterio_de_aceptacion', models.TextField()),
                ('consideraciones', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
