# Generated by Django 5.1.4 on 2025-04-22 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicadores', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indicador',
            options={'verbose_name': 'Indicador', 'verbose_name_plural': 'Indicadores'},
        ),
    ]
