# Generated by Django 5.1.4 on 2025-12-29 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atestado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('enlace_archivo', models.URLField(verbose_name='Enlace al archivo en la nube')),
            ],
            options={
                'verbose_name': 'Atestado-Contrato',
                'verbose_name_plural': 'Atestados-Contratos',
            },
        ),
        migrations.CreateModel(
            name='DescripcionesPuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_puesto', models.CharField(max_length=100, verbose_name='Nombre del puesto')),
                ('salario_base', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salario base')),
                ('pago_adicional', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='pago dicional')),
                ('actividades', models.TextField(verbose_name='Actividades que realiza')),
                ('competencias_requeridas', models.TextField(verbose_name='Competencias requeridas')),
                ('jefe_inmediato', models.CharField(max_length=100, verbose_name='Jefe inmediato (puesto)')),
                ('comentarios', models.TextField(blank=True, null=True, verbose_name='Comentarios')),
            ],
            options={
                'verbose_name': 'Descripción de Puesto',
                'verbose_name_plural': 'Descripciones de Puestos',
            },
        ),
    ]
