# Generated by Django 5.1.4 on 2025-04-18 02:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Competencia',
            new_name='CompetenciaUsuario',
        ),
        migrations.RenameModel(
            old_name='DetalleCompetencia',
            new_name='DetalleCompetenciaUsuario',
        ),
    ]
