# Generated by Django 5.1.4 on 2025-04-18 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0002_rename_competencia_competenciausuario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallecompetenciausuario',
            name='competencia',
        ),
        migrations.DeleteModel(
            name='CompetenciaUsuario',
        ),
        migrations.DeleteModel(
            name='DetalleCompetenciaUsuario',
        ),
    ]
