# Generated by Django 5.1.4 on 2025-04-18 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0003_remove_detallecompetenciausuario_competencia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescripcionesPuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_puesto', models.CharField(max_length=100, verbose_name='Nombre del puesto')),
                ('salario_base', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salario base')),
                ('porcentaje_comision', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='% de comisión')),
                ('actividades', models.TextField(verbose_name='Actividades que realiza')),
                ('competencias_requeridas', models.TextField(verbose_name='Competencias requeridas')),
                ('jefe_inmediato', models.CharField(max_length=100, verbose_name='Jefe inmediato (puesto)')),
                ('comentarios', models.TextField(blank=True, null=True, verbose_name='Comentarios')),
            ],
            options={
                'verbose_name': 'Descripción de Puesto',
                'verbose_name_plural': 'Descripciones de Puestos',
            },
        ),
    ]
