# Generated by Django 5.1.4 on 2025-04-18 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0004_descripcionespuesto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='descripcionespuesto',
            name='porcentaje_comision',
        ),
        migrations.AddField(
            model_name='descripcionespuesto',
            name='pago_adicional',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='pago dicional'),
        ),
    ]
