# Generated by Django 5.1.4 on 2025-04-30 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0005_remove_descripcionespuesto_porcentaje_comision_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atestado',
            options={'verbose_name': 'Atestado-Contrato', 'verbose_name_plural': 'Atestados-Contratos'},
        ),
    ]
