# Generated by Django 5.1.4 on 2025-05-07 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analisis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CAUSA_RAIZ', 'Análisis de Causa Raíz'), ('MODOS_FALLO', 'Análisis de Modos de Fallo'), ('CICLO_VIDA', 'Análisis de Ciclo de Vida'), ('RIESGO', 'Análisis de Riesgo'), ('TENDENCIAS', 'Análisis de Tendencias')], max_length=50)),
                ('descripcion', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_analisis', models.DateTimeField()),
                ('indicadores_incluidos', models.TextField(help_text='Indica los indicadores utilizados en el análisis')),
                ('resultado', models.TextField(help_text='Resumen de los resultados del análisis')),
                ('impacto_estudio', models.TextField(help_text='Impacto del análisis en la operación o producto')),
            ],
            options={
                'verbose_name': 'Análisis',
                'verbose_name_plural': 'Análisis',
            },
        ),
        migrations.CreateModel(
            name='Retroalimentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('fecha_retroalimentacion', models.DateTimeField(auto_now_add=True)),
                ('responsabilidad', models.CharField(max_length=200)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En Proceso'), ('COMPLETADO', 'Completado')], default='PENDIENTE', max_length=50)),
                ('analisis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retroalimentaciones', to='analisis_retroalimentacion.analisis')),
            ],
            options={
                'verbose_name': 'Retroalimentación',
                'verbose_name_plural': 'Retroalimentaciones',
            },
        ),
        migrations.CreateModel(
            name='PlanAccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_accion', models.TextField()),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_limite', models.DateTimeField()),
                ('responsable', models.CharField(max_length=200)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En Proceso'), ('FINALIZADO', 'Finalizado')], default='PENDIENTE', max_length=50)),
                ('retroalimentacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acciones', to='analisis_retroalimentacion.retroalimentacion')),
            ],
            options={
                'verbose_name': 'Plan de Acción',
                'verbose_name_plural': 'Planes de Acción',
            },
        ),
    ]
