# Generated by Django 5.1.4 on 2025-08-10 00:25

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0024_rename_agente_retencion_cliente_sujeto_excluido_and_more'),
        ('cotizaciones', '0022_cotizacion_total_iva'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComprobanteDonacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_donacion', models.TextField(blank=True, null=True)),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'Comprobante de Donación',
                'verbose_name_plural': 'Comprobantes de Donación',
            },
        ),
        migrations.CreateModel(
            name='FacturaSujetoExcluido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Factura Sujeto Excluido',
                'verbose_name_plural': 'Facturas Sujetos Excluidos',
            },
        ),
        migrations.CreateModel(
            name='NotaRemision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion_entrega', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Nota de Remisión',
                'verbose_name_plural': 'Notas de Remisión',
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correlativo', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('tipo_factura', models.CharField(choices=[('01', '(CF), Consumidor Final'), ('03', '(CCF), Comprobante de Crédito Fiscal')], default='01', max_length=4, verbose_name='Tipo de Factura')),
                ('condicion_operacion', models.CharField(choices=[('01', 'Contado'), ('02', 'Crédito'), ('05', 'Donación'), ('07', 'Otros')], default=None, max_length=20, verbose_name='Condición de Operación')),
                ('ventas_no_sujetas', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True)),
                ('ventas_exentas', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True)),
                ('ventas_gravadas', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True)),
                ('total_sin_iva', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('iva', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True)),
                ('iva_retenido', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True)),
                ('iva_percibido', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True)),
                ('total_con_iva', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_letras', models.CharField(blank=True, max_length=255, null=True, verbose_name='Total en Letras')),
                ('codigo_generacion', models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='Código de Generación')),
                ('respuesta_firmador', models.TextField(blank=True, null=True)),
                ('respuesta_hacienda', models.TextField(blank=True, null=True)),
                ('idenvio_hacienda', models.CharField(blank=True, max_length=64, null=True)),
                ('numero_control', models.CharField(blank=True, max_length=64, null=True)),
                ('sello_recepcion', models.CharField(blank=True, max_length=128, null=True)),
                ('version_dte', models.CharField(blank=True, max_length=10, null=True)),
                ('version_json', models.CharField(blank=True, max_length=16, null=True)),
                ('fecha_envio', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('firma', models.TextField(blank=True, null=True)),
                ('json_dte', models.JSONField(blank=True, null=True)),
                ('json_firmado', models.JSONField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('estado_envio_hacienda', models.CharField(choices=[('pendiente', 'Pendiente'), ('firmado', 'Firmado'), ('enviado', 'Enviado'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('cotizacion', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cotizaciones.cotizacion')),
            ],
            options={
                'verbose_name': 'Venta-facturacion',
                'verbose_name_plural': 'Ventas-facturacion',
            },
        ),
        migrations.CreateModel(
            name='ComprobanteRetencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correlativo_r', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('monto_retenido_iva', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_retenido_renta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('factura_referencia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comprobantes_retencion', to='facturacion.factura')),
            ],
            options={
                'verbose_name': 'Comprobante de Retención',
                'verbose_name_plural': 'Comprobantes de Retención',
            },
        ),
        migrations.CreateModel(
            name='Anulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_anulacion', models.TextField(blank=True, null=True)),
                ('factura_anular', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Anulaciones', to='facturacion.factura')),
            ],
            options={
                'verbose_name': 'Anulacion',
                'verbose_name_plural': 'Anulaciones',
            },
        ),
        migrations.CreateModel(
            name='NotaCreditoDebito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_nota', models.CharField(choices=[('05', '(NC), Nota de Crédito'), ('06', '(ND), Nota de Débito')], default='05', max_length=4, verbose_name='Tipo de Nota')),
                ('motivo', models.TextField()),
                ('correlativo_n', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('nuevo_monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('factura_referencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='facturacion.factura')),
            ],
            options={
                'verbose_name': 'Nota de Credito/Debito',
                'verbose_name_plural': 'Notas de Credito/Debito',
            },
        ),
    ]
