# Generated by Django 5.1.4 on 2025-08-07 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notacreditodebito',
            old_name='factura',
            new_name='factura_referencia',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='fecha_facturacion',
        ),
        migrations.RemoveField(
            model_name='notacreditodebito',
            name='tipo',
        ),
    ]
