# Generated by Django 5.1.4 on 2025-08-10 02:05

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0024_rename_agente_retencion_cliente_sujeto_excluido_and_more'),
        ('cotizaciones', '0022_cotizacion_total_iva'),
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comprobanteretencion',
            old_name='correlativo_r',
            new_name='correlativo',
        ),
        migrations.RenameField(
            model_name='notacreditodebito',
            old_name='correlativo_n',
            new_name='correlativo',
        ),
        migrations.AddField(
            model_name='anulacion',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='anulacion',
            name='codigo_generacion',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='Código de Generación'),
        ),
        migrations.AddField(
            model_name='anulacion',
            name='condicion_operacion',
            field=models.CharField(choices=[('01', 'Contado'), ('02', 'Crédito'), ('05', 'Donación'), ('07', 'Otros')], default=None, max_length=20, verbose_name='Condición de Operación'),
        ),
        migrations.AddField(
            model_name='anulacion',
            name='correlativo',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='anulacion',
            name='estado_envio_hacienda',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('firmado', 'Firmado'), ('enviado', 'Enviado'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='anulacion',
            name='fecha_envio',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='anulacion',
            name='firma',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anulacion',
            name='idenvio_hacienda',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='anulacion',
            name='json_dte',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anulacion',
            name='json_firmado',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anulacion',
            name='numero_control',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='anulacion',
            name='respuesta_firmador',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anulacion',
            name='respuesta_hacienda',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anulacion',
            name='sello_recepcion',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='anulacion',
            name='tipo_factura',
            field=models.CharField(choices=[('01', '(CF), Consumidor Final'), ('03', '(CCF), Comprobante de Crédito Fiscal')], default='01', max_length=4, verbose_name='Tipo de Factura'),
        ),
        migrations.AddField(
            model_name='anulacion',
            name='version_dte',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='anulacion',
            name='version_json',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='comprobantedonacion',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='comprobantedonacion',
            name='codigo_generacion',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='Código de Generación'),
        ),
        migrations.AddField(
            model_name='comprobantedonacion',
            name='condicion_operacion',
            field=models.CharField(choices=[('01', 'Contado'), ('02', 'Crédito'), ('05', 'Donación'), ('07', 'Otros')], default=None, max_length=20, verbose_name='Condición de Operación'),
        ),
        migrations.AddField(
            model_name='comprobantedonacion',
            name='correlativo',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='comprobantedonacion',
            name='estado_envio_hacienda',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('firmado', 'Firmado'), ('enviado', 'Enviado'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='comprobantedonacion',
            name='fecha_envio',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='comprobantedonacion',
            name='firma',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comprobantedonacion',
            name='idenvio_hacienda',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='comprobantedonacion',
            name='json_dte',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comprobantedonacion',
            name='json_firmado',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comprobantedonacion',
            name='numero_control',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='comprobantedonacion',
            name='respuesta_firmador',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comprobantedonacion',
            name='respuesta_hacienda',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comprobantedonacion',
            name='sello_recepcion',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='comprobantedonacion',
            name='tipo_factura',
            field=models.CharField(choices=[('01', '(CF), Consumidor Final'), ('03', '(CCF), Comprobante de Crédito Fiscal')], default='01', max_length=4, verbose_name='Tipo de Factura'),
        ),
        migrations.AddField(
            model_name='comprobantedonacion',
            name='version_dte',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='comprobantedonacion',
            name='version_json',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='comprobanteretencion',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='comprobanteretencion',
            name='condicion_operacion',
            field=models.CharField(choices=[('01', 'Contado'), ('02', 'Crédito'), ('05', 'Donación'), ('07', 'Otros')], default=None, max_length=20, verbose_name='Condición de Operación'),
        ),
        migrations.AddField(
            model_name='comprobanteretencion',
            name='tipo_factura',
            field=models.CharField(choices=[('01', '(CF), Consumidor Final'), ('03', '(CCF), Comprobante de Crédito Fiscal')], default='01', max_length=4, verbose_name='Tipo de Factura'),
        ),
        migrations.AddField(
            model_name='facturasujetoexcluido',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='facturasujetoexcluido',
            name='codigo_generacion',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='Código de Generación'),
        ),
        migrations.AddField(
            model_name='facturasujetoexcluido',
            name='condicion_operacion',
            field=models.CharField(choices=[('01', 'Contado'), ('02', 'Crédito'), ('05', 'Donación'), ('07', 'Otros')], default=None, max_length=20, verbose_name='Condición de Operación'),
        ),
        migrations.AddField(
            model_name='facturasujetoexcluido',
            name='correlativo',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='facturasujetoexcluido',
            name='cotizacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cotizaciones.cotizacion'),
        ),
        migrations.AddField(
            model_name='facturasujetoexcluido',
            name='estado_envio_hacienda',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('firmado', 'Firmado'), ('enviado', 'Enviado'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='facturasujetoexcluido',
            name='fecha_envio',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='facturasujetoexcluido',
            name='firma',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facturasujetoexcluido',
            name='idenvio_hacienda',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='facturasujetoexcluido',
            name='iva',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='facturasujetoexcluido',
            name='iva_percibido',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='facturasujetoexcluido',
            name='iva_retenido',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='facturasujetoexcluido',
            name='json_dte',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facturasujetoexcluido',
            name='json_firmado',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facturasujetoexcluido',
            name='numero_control',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='facturasujetoexcluido',
            name='respuesta_firmador',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facturasujetoexcluido',
            name='respuesta_hacienda',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facturasujetoexcluido',
            name='sello_recepcion',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='facturasujetoexcluido',
            name='tipo_factura',
            field=models.CharField(choices=[('01', '(CF), Consumidor Final'), ('03', '(CCF), Comprobante de Crédito Fiscal')], default='01', max_length=4, verbose_name='Tipo de Factura'),
        ),
        migrations.AddField(
            model_name='facturasujetoexcluido',
            name='total_con_iva',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='facturasujetoexcluido',
            name='total_sin_iva',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='facturasujetoexcluido',
            name='ventas_exentas',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='facturasujetoexcluido',
            name='ventas_gravadas',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='facturasujetoexcluido',
            name='ventas_no_sujetas',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='facturasujetoexcluido',
            name='version_dte',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='facturasujetoexcluido',
            name='version_json',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='notacreditodebito',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='notacreditodebito',
            name='codigo_generacion',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='Código de Generación'),
        ),
        migrations.AddField(
            model_name='notacreditodebito',
            name='condicion_operacion',
            field=models.CharField(choices=[('01', 'Contado'), ('02', 'Crédito'), ('05', 'Donación'), ('07', 'Otros')], default=None, max_length=20, verbose_name='Condición de Operación'),
        ),
        migrations.AddField(
            model_name='notacreditodebito',
            name='estado_envio_hacienda',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('firmado', 'Firmado'), ('enviado', 'Enviado'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='notacreditodebito',
            name='fecha_envio',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='notacreditodebito',
            name='firma',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notacreditodebito',
            name='idenvio_hacienda',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='notacreditodebito',
            name='json_dte',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notacreditodebito',
            name='json_firmado',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notacreditodebito',
            name='nuevo_monto_letras',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Total en Letras'),
        ),
        migrations.AddField(
            model_name='notacreditodebito',
            name='numero_control',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='notacreditodebito',
            name='respuesta_firmador',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notacreditodebito',
            name='respuesta_hacienda',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notacreditodebito',
            name='sello_recepcion',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='notacreditodebito',
            name='tipo_factura',
            field=models.CharField(choices=[('01', '(CF), Consumidor Final'), ('03', '(CCF), Comprobante de Crédito Fiscal')], default='01', max_length=4, verbose_name='Tipo de Factura'),
        ),
        migrations.AddField(
            model_name='notacreditodebito',
            name='version_dte',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='notacreditodebito',
            name='version_json',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='notaremision',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='notaremision',
            name='codigo_generacion',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='Código de Generación'),
        ),
        migrations.AddField(
            model_name='notaremision',
            name='condicion_operacion',
            field=models.CharField(choices=[('01', 'Contado'), ('02', 'Crédito'), ('05', 'Donación'), ('07', 'Otros')], default=None, max_length=20, verbose_name='Condición de Operación'),
        ),
        migrations.AddField(
            model_name='notaremision',
            name='correlativo',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='notaremision',
            name='estado_envio_hacienda',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('firmado', 'Firmado'), ('enviado', 'Enviado'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='notaremision',
            name='fecha_envio',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='notaremision',
            name='firma',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notaremision',
            name='idenvio_hacienda',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='notaremision',
            name='json_dte',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notaremision',
            name='json_firmado',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notaremision',
            name='numero_control',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='notaremision',
            name='respuesta_firmador',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notaremision',
            name='respuesta_hacienda',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notaremision',
            name='sello_recepcion',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='notaremision',
            name='tipo_factura',
            field=models.CharField(choices=[('01', '(CF), Consumidor Final'), ('03', '(CCF), Comprobante de Crédito Fiscal')], default='01', max_length=4, verbose_name='Tipo de Factura'),
        ),
        migrations.AddField(
            model_name='notaremision',
            name='version_dte',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='notaremision',
            name='version_json',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
