# Generated by Django 5.1.4 on 2025-08-07 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0002_rename_factura_notacreditodebito_factura_referencia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturasujetoexcluido',
            name='fecha_emision',
        ),
    ]
