# Generated by Django 5.1.4 on 2025-08-10 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0002_rename_correlativo_r_comprobanteretencion_correlativo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anulacion',
            name='condicion_operacion',
            field=models.CharField(choices=[('01', 'Contado'), ('02', 'Crédito'), ('05', 'Donación'), ('07', 'Otros')], default='01', max_length=20, verbose_name='Condición de Operación'),
        ),
        migrations.AlterField(
            model_name='comprobantedonacion',
            name='tipo_factura',
            field=models.CharField(choices=[('15', '(CD), Comprobante de Donación')], default='01', max_length=4, verbose_name='Tipo de Factura'),
        ),
        migrations.AlterField(
            model_name='comprobanteretencion',
            name='condicion_operacion',
            field=models.CharField(choices=[('01', 'Contado'), ('02', 'Crédito'), ('05', 'Donación'), ('07', 'Otros')], default='01', max_length=20, verbose_name='Condición de Operación'),
        ),
        migrations.AlterField(
            model_name='comprobanteretencion',
            name='tipo_factura',
            field=models.CharField(choices=[('07', '(CR), Comprobante de Retención')], default='01', max_length=4, verbose_name='Tipo de Factura'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='condicion_operacion',
            field=models.CharField(choices=[('01', 'Contado'), ('02', 'Crédito'), ('05', 'Donación'), ('07', 'Otros')], default='01', max_length=20, verbose_name='Condición de Operación'),
        ),
        migrations.AlterField(
            model_name='facturasujetoexcluido',
            name='condicion_operacion',
            field=models.CharField(choices=[('01', 'Contado'), ('02', 'Crédito'), ('05', 'Donación'), ('07', 'Otros')], default='01', max_length=20, verbose_name='Condición de Operación'),
        ),
        migrations.AlterField(
            model_name='facturasujetoexcluido',
            name='tipo_factura',
            field=models.CharField(choices=[('14', '(FS), Factura Sujeto Excluido')], default='01', max_length=4, verbose_name='Tipo de Factura'),
        ),
        migrations.AlterField(
            model_name='notacreditodebito',
            name='condicion_operacion',
            field=models.CharField(choices=[('01', 'Contado'), ('02', 'Crédito'), ('05', 'Donación'), ('07', 'Otros')], default='01', max_length=20, verbose_name='Condición de Operación'),
        ),
        migrations.AlterField(
            model_name='notaremision',
            name='condicion_operacion',
            field=models.CharField(choices=[('01', 'Contado'), ('02', 'Crédito'), ('05', 'Donación'), ('07', 'Otros')], default='01', max_length=20, verbose_name='Condición de Operación'),
        ),
        migrations.AlterField(
            model_name='notaremision',
            name='tipo_factura',
            field=models.CharField(choices=[('04', '(NR), Nota de Remisión')], default='01', max_length=4, verbose_name='Tipo de Factura'),
        ),
    ]
