# Generated by Django 5.1.4 on 2025-08-07 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0003_remove_facturasujetoexcluido_fecha_emision'),
    ]

    operations = [
        migrations.AddField(
            model_name='notacreditodebito',
            name='tipo_nota',
            field=models.CharField(choices=[('05', '(NC), Nota de Crédito'), ('06', '(ND), Nota de Débito')], default='05', max_length=4, verbose_name='Tipo de Nota'),
        ),
    ]
