# Generated by Django 5.1.4 on 2025-08-10 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0003_alter_anulacion_condicion_operacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notacreditodebito',
            name='condicion_operacion',
            field=models.CharField(blank=True, choices=[('01', 'Contado'), ('02', 'Crédito'), ('05', 'Donación'), ('07', 'Otros')], default='01', max_length=20, null=True, verbose_name='Condición de Operación'),
        ),
    ]
