# Generated by Django 5.1.4 on 2025-08-07 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0004_notacreditodebito_tipo_nota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='tipo_factura',
            field=models.CharField(choices=[('01', '(CF), Consumidor Final'), ('03', '(CCF), Comprobante de Crédito Fiscal')], default='01', max_length=4, verbose_name='Tipo de Factura'),
        ),
    ]
