# Generated by Django 5.1.4 on 2025-08-07 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0005_alter_factura_tipo_factura'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anulacion',
            fields=[
                ('factura_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='facturacion.factura')),
                ('factura_anulada', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Anulaciones', to='facturacion.factura')),
            ],
            options={
                'verbose_name': 'Anulacion',
                'verbose_name_plural': 'Anulaciones',
            },
            bases=('facturacion.factura',),
        ),
    ]
