# Generated by Django 5.1.4 on 2025-08-07 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0006_anulacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comprobanteretencion',
            options={'verbose_name': 'Comprobante de Retención', 'verbose_name_plural': 'Comprobantes de Retención'},
        ),
    ]
