# Generated by Django 5.1.4 on 2025-08-08 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0007_alter_comprobanteretencion_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobanteretencion',
            name='correlativo_r',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='notacreditodebito',
            name='correlativo_n',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
