# Generated by Django 5.1.4 on 2025-08-09 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0008_comprobanteretencion_correlativo_r_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anulacion',
            old_name='factura_anulada',
            new_name='factura_anular',
        ),
        migrations.AddField(
            model_name='anulacion',
            name='descripcion_anulacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
