# Generated by Django 5.1.4 on 2025-04-27 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('responsable', models.CharField(max_length=100)),
                ('observaciones', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='NoConformidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('fecha_detectada', models.DateField()),
                ('gravedad', models.CharField(choices=[('Menor', 'Menor'), ('Mayor', 'Mayor'), ('Crítica', 'Crítica')], max_length=50)),
                ('estatus', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Proceso', 'En Proceso'), ('Resuelto', 'Resuelto')], default='Pendiente', max_length=50)),
                ('auditoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_calidad.auditoria')),
            ],
        ),
        migrations.CreateModel(
            name='AccionCorrectiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('responsable', models.CharField(max_length=100)),
                ('fecha_compromiso', models.DateField()),
                ('fecha_cierre', models.DateField(blank=True, null=True)),
                ('no_conformidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_calidad.noconformidad')),
            ],
        ),
        migrations.AddField(
            model_name='auditoria',
            name='proceso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_calidad.proceso'),
        ),
    ]
