# Generated by Django 5.1.4 on 2025-05-07 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_calidad', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noconformidad',
            options={'verbose_name': 'No conformidad', 'verbose_name_plural': 'No conformidades'},
        ),
    ]
