# Generated by Django 5.1.4 on 2025-02-07 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('categoria', models.CharField(max_length=100)),
                ('especialidad', models.CharField(max_length=100)),
                ('descripción', models.CharField(max_length=200)),
            ],
        ),
    ]
