# Generated by Django 5.1.4 on 2025-12-29 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('correlativo', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('especialidad', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=200)),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('descripcion_unidad', models.CharField(default='Unidades para el precio unitario, ej. por milla', max_length=100)),
                ('notas', models.CharField(default='consideraciones', max_length=100)),
            ],
        ),
    ]
