# Generated by Django 5.1.4 on 2026-02-26 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0002_alter_equipo_especificaciones_alter_equipo_ubicacion_and_more'),
        ('proveedores', '0001_initial'),
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='equipo',
            field=models.ManyToManyField(blank=True, to='equipos.equipo'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='factura_compra',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='fecha_compra',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proveedores.proveedor'),
        ),
    ]
