# Generated by Django 5.1.4 on 2025-04-23 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_servicio_preciounitario'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='notas',
            field=models.CharField(default='consideraciones', max_length=100),
        ),
        migrations.AddField(
            model_name='servicio',
            name='unidades_unitarias',
            field=models.CharField(default='Unidades para el precio unitario, ej. por milla', max_length=100),
        ),
    ]
