# Generated by Django 5.1.4 on 2026-02-27 00:02

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_servicio_equipo_servicio_factura_compra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='descripcion',
            field=core.fields.RichTextMediumField(max_length=200),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='especialidad',
            field=core.fields.RichTextMediumField(max_length=100),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='nombre',
            field=core.fields.RichTextMediumField(max_length=100),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='notas',
            field=core.fields.RichTextMediumField(default='consideraciones', max_length=100),
        ),
    ]
