# Generated by Django 5.1.4 on 2026-03-20 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0003_alter_servicio_descripcion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='equipo',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='factura_compra',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='fecha_compra',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='proveedor',
        ),
    ]
