# Generated by Django 5.1.4 on 2025-04-23 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0003_servicio_notas_servicio_unidades_unitarias'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicio',
            old_name='unidades_unitarias',
            new_name='descripcion_unidad',
        ),
    ]
