# Generated by Django 5.1.4 on 2025-05-29 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0004_rename_unidades_unitarias_servicio_descripcion_unidad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicio',
            old_name='PrecioUnitario',
            new_name='Precio_unitario',
        ),
    ]
