# Generated by Django 5.1.4 on 2026-03-27 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0004_remove_servicio_equipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='especialidad',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
