# Generated by Django 5.1.4 on 2025-05-29 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0005_rename_preciounitario_servicio_precio_unitario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicio',
            old_name='Precio_unitario',
            new_name='precio_unitario',
        ),
    ]
