# Generated by Django 5.1.4 on 2025-06-08 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0006_rename_precio_unitario_servicio_precio_unitario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicio',
            old_name='descripción',
            new_name='descripcion',
        ),
    ]
