# Generated by Django 5.1.4 on 2025-06-13 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0007_rename_descripción_servicio_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='correlativo',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
