# Generated by Django 5.1.4 on 2025-06-22 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0008_servicio_correlativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='correlativo',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
