# Generated by Django 5.1.4 on 2025-07-29 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0009_alter_servicio_correlativo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicio',
            old_name='categoria',
            new_name='nombre',
        ),
    ]
