# Generated by Django 5.1.4 on 2025-12-29 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cotizaciones', '0001_initial'),
        ('documentacion', '0001_initial'),
        ('equipos', '0001_initial'),
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_plan', models.CharField(default='PM-001', max_length=100, unique=True)),
                ('descripcion', models.TextField(default='Plan de mantenimiento personalizado')),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('fecha_modificacion', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plan de mantenimiento',
                'verbose_name_plural': 'Planes de mantenimiento',
            },
        ),
        migrations.CreateModel(
            name='DetallePlanMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo_actividad', models.CharField(blank=True, max_length=500)),
                ('frecuencia', models.CharField(choices=[('8h', 'Cada 8 horas'), ('diario', 'Diario'), ('semanal', 'Semanal'), ('mensual', 'Mensual'), ('bimensual', 'Bimensual'), ('trimestral', 'Trimestral'), ('semestral', 'Semestral'), ('anual', 'Anual'), ('personalizado', 'Personalizado')], default='mensual', max_length=20)),
                ('fechainicio', models.DateField()),
                ('horarios_actividad', models.CharField(choices=[('AM', 'Matutino 6-3'), ('PM', 'Vespertino 12-9'), ('PM2', 'Nocturno 9-6'), ('8-5', 'Horario Normal 8-5')], default='8-5', max_length=4)),
                ('cantidad_autogenerada', models.PositiveIntegerField(default=1, help_text='Número de OTs futuras a generar automáticamente.')),
                ('especialista', models.CharField(blank=True, max_length=100)),
                ('cantidad_personas', models.PositiveIntegerField(blank=True, default=1)),
                ('tiempo_realizacion_estimado', models.DurationField(blank=True, null=True)),
                ('hora_realizacion_estimada', models.TimeField(blank=True, null=True)),
                ('proxima_fecha', models.DateTimeField(blank=True, null=True)),
                ('notas', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cotizacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cotizacion', to='cotizaciones.cotizacion')),
                ('herramientas', models.ManyToManyField(blank=True, to='equipos.herramienta')),
                ('procedimiento', models.ManyToManyField(blank=True, to='documentacion.documentacion')),
                ('proveedores', models.ManyToManyField(blank=True, to='proveedores.proveedor')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='planes_mantenimiento.planmantenimiento')),
            ],
        ),
    ]
