# Generated by Django 5.1.4 on 2025-06-22 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documentacion', '0003_alter_documentacion_options'),
        ('equipos', '0010_herramienta'),
        ('proveedores', '0005_remove_proveedor_contacto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(default='Plan de mantenimiento personalizado')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipos.equipo')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePlanMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad', models.CharField(max_length=500)),
                ('motivo_actividad', models.CharField(max_length=500)),
                ('frecuencia', models.CharField(max_length=100)),
                ('especialidad', models.CharField(max_length=100)),
                ('especialista', models.CharField(max_length=100)),
                ('herramientas', models.CharField(default='caja de herramientas', max_length=500)),
                ('cantidad_personas', models.PositiveIntegerField(default=1)),
                ('tiempo_realizacion_estimado', models.DurationField()),
                ('hora_realizacion_estimada', models.TimeField(blank=True, null=True)),
                ('notas', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('procedimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documentacion.documentacion')),
                ('proveedores', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedores.proveedor')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='planes_mantenimiento.planmantenimiento')),
            ],
        ),
    ]
