# Generated by Django 5.1.4 on 2025-12-02 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes_mantenimiento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planmantenimiento',
            name='codigo_plan',
            field=models.CharField(default='PM-001', max_length=100, unique=True),
        ),
    ]
