# Generated by Django 5.1.4 on 2026-02-27 00:02

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planes_mantenimiento', '0002_alter_detalleplanmantenimiento_frecuencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleplanmantenimiento',
            name='notas',
            field=core.fields.RichTextSimpleField(blank=True),
        ),
        migrations.AlterField(
            model_name='planmantenimiento',
            name='descripcion',
            field=core.fields.RichTextSimpleField(default='Plan de mantenimiento personalizado'),
        ),
    ]
