# Generated by Django 5.1.4 on 2025-12-11 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0029_alter_cotizacion_equipo'),
        ('equipos', '0019_alter_historialtrabajos_fecha_registro'),
        ('planes_mantenimiento', '0002_planmantenimiento_codigo_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleplanmantenimiento',
            name='actividad',
        ),
        migrations.RemoveField(
            model_name='detalleplanmantenimiento',
            name='especialidad',
        ),
        migrations.AddField(
            model_name='detalleplanmantenimiento',
            name='cotizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cotizacion', to='cotizaciones.cotizacion'),
        ),
        migrations.AddField(
            model_name='detalleplanmantenimiento',
            name='fechainicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detalleplanmantenimiento',
            name='frecuencia',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='detalleplanmantenimiento',
            name='herramientas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotizacion', to='equipos.herramienta'),
        ),
        migrations.RemoveField(
            model_name='planmantenimiento',
            name='equipo',
        ),
        migrations.AddField(
            model_name='planmantenimiento',
            name='equipo',
            field=models.ManyToManyField(blank=True, to='equipos.equipo'),
        ),
    ]
