# Generated by Django 5.1.4 on 2025-12-11 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes_mantenimiento', '0003_remove_detalleplanmantenimiento_actividad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleplanmantenimiento',
            name='fechainicio',
            field=models.DateField(),
        ),
    ]
