# Generated by Django 5.1.4 on 2026-05-08 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes_mantenimiento', '0003_alter_detalleplanmantenimiento_notas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planmantenimiento',
            name='descripcion',
            field=models.TextField(default='Plan de mantenimiento personalizado'),
        ),
    ]
