# Generated by Django 5.1.4 on 2025-12-11 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes_mantenimiento', '0004_alter_detalleplanmantenimiento_fechainicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleplanmantenimiento',
            name='frecuencia',
            field=models.CharField(choices=[('8h', 'Cada 8 horas'), ('diario', 'Diario'), ('semanal', 'Semanal'), ('mensual', 'Mensual'), ('bimensual', 'Bimensual'), ('trimestral', 'Trimestral'), ('semestral', 'Semestral'), ('anual', 'Anual'), ('personalizado', 'Personalizado')], default='mensual', max_length=20),
        ),
    ]
