# Generated by Django 5.1.4 on 2025-12-11 18:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentacion', '0003_alter_documentacion_options'),
        ('equipos', '0019_alter_historialtrabajos_fecha_registro'),
        ('planes_mantenimiento', '0005_alter_detalleplanmantenimiento_frecuencia'),
        ('proveedores', '0010_proveedor_correlativo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planmantenimiento',
            name='equipo',
        ),
        migrations.AddField(
            model_name='planmantenimiento',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='planmantenimiento',
            name='fecha_modificacion',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='detalleplanmantenimiento',
            name='cantidad_personas',
            field=models.PositiveIntegerField(blank=True, default=1),
        ),
        migrations.RemoveField(
            model_name='detalleplanmantenimiento',
            name='herramientas',
        ),
        migrations.RemoveField(
            model_name='detalleplanmantenimiento',
            name='procedimiento',
        ),
        migrations.RemoveField(
            model_name='detalleplanmantenimiento',
            name='proveedores',
        ),
        migrations.AddField(
            model_name='detalleplanmantenimiento',
            name='herramientas',
            field=models.ManyToManyField(blank=True, to='equipos.herramienta'),
        ),
        migrations.AddField(
            model_name='detalleplanmantenimiento',
            name='procedimiento',
            field=models.ManyToManyField(blank=True, to='documentacion.documentacion'),
        ),
        migrations.AddField(
            model_name='detalleplanmantenimiento',
            name='proveedores',
            field=models.ManyToManyField(blank=True, to='proveedores.proveedor'),
        ),
    ]
