# Generated by Django 5.1.4 on 2025-12-11 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes_mantenimiento', '0006_remove_planmantenimiento_equipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleplanmantenimiento',
            name='proxima_fecha',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
