# Generated by Django 5.1.4 on 2025-12-12 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes_mantenimiento', '0007_detalleplanmantenimiento_proxima_fecha'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planmantenimiento',
            options={'verbose_name': 'Plan de mantenimiento', 'verbose_name_plural': 'Planes de mantenimiento'},
        ),
        migrations.AddField(
            model_name='detalleplanmantenimiento',
            name='cantidad_autogenerada',
            field=models.PositiveIntegerField(default=1, help_text='Número de OTs futuras a generar automáticamente.'),
        ),
    ]
