# Generated by Django 5.1.4 on 2025-12-12 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0029_alter_cotizacion_equipo'),
        ('planes_mantenimiento', '0008_alter_planmantenimiento_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleplanmantenimiento',
            name='cotizacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cotizacion', to='cotizaciones.cotizacion'),
        ),
        migrations.AlterField(
            model_name='detalleplanmantenimiento',
            name='especialista',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='detalleplanmantenimiento',
            name='motivo_actividad',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='detalleplanmantenimiento',
            name='tiempo_realizacion_estimado',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
