# Generated by Django 5.1.4 on 2025-12-12 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes_mantenimiento', '0009_alter_detalleplanmantenimiento_cotizacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleplanmantenimiento',
            name='horarios_actividad',
            field=models.CharField(choices=[('AM', 'Matutino 6-3'), ('PM', 'Vespertino 12-9'), ('PM2', 'Nocturno 9-6'), ('8-5', 'Horario Normal 8-5')], default='8-5', max_length=4),
        ),
    ]
