# Generated by Django 5.1.4 on 2025-08-10 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notacreditodebito',
            name='tipo_factura',
        ),
    ]
