# Generated by Django 5.1.4 on 2025-08-10 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0002_remove_notacreditodebito_tipo_factura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notacreditodebito',
            name='factura_referencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='facturacion.factura', verbose_name='Factura Referencia (solo creditos fiscales)'),
        ),
    ]
