# Generated by Django 5.1.4 on 2025-08-11 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0003_alter_notacreditodebito_factura_referencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='notaremision',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
