# Generated by Django 5.1.4 on 2025-08-12 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0004_notaremision_monto'),
    ]

    operations = [
        migrations.AddField(
            model_name='notaremision',
            name='factura_entrega',
            field=models.ForeignKey(
                default=1,  # <-- asignar un valor por defecto válido
                on_delete=django.db.models.deletion.CASCADE,
                related_name='notas_remision',
                to='facturacion.factura',
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notaremision',
            name='tipo_factura',
            field=models.CharField(choices=[('04', '(NR), Nota de Remisión')], default='04', max_length=4, verbose_name='Tipo de Factura'),
        ),
    ]
