# Generated by Django 5.1.4 on 2025-08-12 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0008_alter_notaremision_factura_entrega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notaremision',
            name='factura_entrega',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notas_remision', to='facturacion.factura', verbose_name='Factura Referencia (solo creditos fiscales)'),
        ),
    ]
