# Generated by Django 5.1.4 on 2025-08-13 04:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0010_alter_notaremision_factura_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobanteretencion',
            name='codigo_generacion',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='Código de Generación'),
        ),
        migrations.AddField(
            model_name='comprobanteretencion',
            name='estado_envio_hacienda',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('firmado', 'Firmado'), ('enviado', 'Enviado'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='comprobanteretencion',
            name='fecha_envio',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='comprobanteretencion',
            name='firma',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comprobanteretencion',
            name='idenvio_hacienda',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='comprobanteretencion',
            name='json_dte',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comprobanteretencion',
            name='json_firmado',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comprobanteretencion',
            name='numero_control',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='comprobanteretencion',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comprobanteretencion',
            name='respuesta_firmador',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comprobanteretencion',
            name='respuesta_hacienda',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comprobanteretencion',
            name='sello_recepcion',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='comprobanteretencion',
            name='version_dte',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='comprobanteretencion',
            name='version_json',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='facturasujetoexcluido',
            name='tipo_factura',
            field=models.CharField(choices=[('14', '(FS), Factura Sujeto Excluido')], default='14', max_length=4, verbose_name='Tipo de Factura'),
        ),
        migrations.AlterField(
            model_name='notaremision',
            name='factura_entrega',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notas_remision', to='facturacion.factura', verbose_name='Factura entrega (solo creditos fiscales)'),
        ),
    ]
