# Generated by Django 5.1.4 on 2025-08-13 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0011_comprobanteretencion_codigo_generacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobantedonacion',
            name='descripcion_donacion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='comprobantedonacion',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto de la Donación'),
        ),
        migrations.AlterField(
            model_name='comprobanteretencion',
            name='tipo_factura',
            field=models.CharField(choices=[('07', '(CR), Comprobante de Retención')], default='07', max_length=4, verbose_name='Tipo de Factura'),
        ),
    ]
