# Generated by Django 5.1.4 on 2025-08-13 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0012_alter_comprobantedonacion_descripcion_donacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobantedonacion',
            name='descripcion_donacion',
            field=models.TextField(default='', verbose_name='Descripción de la Donación'),
        ),
    ]
