# Generated by Django 5.1.4 on 2025-08-13 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0013_alter_comprobantedonacion_descripcion_donacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comprobantedonacion',
            old_name='cliente',
            new_name='donante',
        ),
        migrations.AlterField(
            model_name='comprobantedonacion',
            name='tipo_factura',
            field=models.CharField(choices=[('15', '(CD), Comprobante de Donación')], default='15', max_length=4, verbose_name='Tipo de Factura'),
        ),
    ]
