# Generated by Django 5.1.4 on 2025-08-13 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0014_rename_cliente_comprobantedonacion_donante_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comprobantedonacion',
            old_name='donante',
            new_name='donatario',
        ),
    ]
