# Generated by Django 5.1.4 on 2025-08-14 00:00

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0015_rename_donante_comprobantedonacion_donatario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anulacion',
            name='descripcion_anulacion',
        ),
        migrations.AddField(
            model_name='anulacion',
            name='codigo_generacion_anulado',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='Código de Generación'),
        ),
        migrations.AddField(
            model_name='anulacion',
            name='iva',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='anulacion',
            name='iva_percibido',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='anulacion',
            name='iva_retenido',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='anulacion',
            name='motivo_anulacion',
            field=models.TextField(default='Anulación por error en la factura'),
        ),
        migrations.AddField(
            model_name='anulacion',
            name='responsable_anulacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='anulaciones_responsable', to=settings.AUTH_USER_MODEL, verbose_name='Responsable de Anulación'),
        ),
        migrations.AddField(
            model_name='anulacion',
            name='tipo_anulacion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='anulacion',
            name='total_con_iva',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='anulacion',
            name='total_letras',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Total en Letras'),
        ),
        migrations.AddField(
            model_name='anulacion',
            name='total_sin_iva',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='anulacion',
            name='ventas_exentas',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='anulacion',
            name='ventas_gravadas',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='anulacion',
            name='ventas_no_sujetas',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='anulacion',
            name='tipo_factura',
            field=models.CharField(choices=[('01', '(CF), Consumidor Final'), ('03', '(CCF), Comprobante de Crédito Fiscal'), ('05', '(NC), Nota de Crédito'), ('06', '(ND), Nota de Débito'), ('04', '(NR), Nota de Remisión'), ('07', '(CR), Comprobante de Retención'), ('14', '(FS), Factura Sujeto Excluido'), ('15', '(CD), Comprobante de Donación')], default='01', max_length=4, verbose_name='Tipo de Factura'),
        ),
    ]
