# Generated by Django 5.1.4 on 2025-08-14 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0016_remove_anulacion_descripcion_anulacion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anulacion',
            old_name='codigo_generacion_anulado',
            new_name='codigo_generacion_r',
        ),
    ]
