# Generated by Django 5.1.4 on 2025-08-14 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0017_rename_codigo_generacion_anulado_anulacion_codigo_generacion_r'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='estado_envio_hacienda',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('firmado', 'Firmado'), ('enviado', 'Enviado'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('anulado', 'Anulado')], default='pendiente', max_length=20),
        ),
    ]
