# Generated by Django 5.1.4 on 2025-08-14 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0018_alter_factura_estado_envio_hacienda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anulacion',
            name='motivo_anulacion',
            field=models.TextField(default='Anulación por cancelación de factura'),
        ),
    ]
