# Generated by Django 5.1.4 on 2025-09-03 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0020_factura_evento_contingencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='motivo_contingencia',
            field=models.CharField(choices=[(1, 'No disponibilidad de sistema del MH'), (2, 'No disponibilidad de sistema del Emisor'), (3, 'Falla en el suministro de servicio de internet del Emisor'), (4, 'Falla en el suministro de energia eléctrica del Emisor'), (5, 'Otra falla no especificada')], default='01', max_length=50, verbose_name='Especifique el motivo de contingencia'),
        ),
    ]
