# Generated by Django 5.1.4 on 2025-09-03 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0022_alter_factura_motivo_contingencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='motivo_contingencia',
            field=models.CharField(choices=[('1', 'sist MH'), ('2', 'sist Emisor'), ('3', 'internet'), ('4', 'eléctrica'), ('5', 'Otra falla')], default='1', max_length=10, verbose_name='Especifique el motivo de contingencia'),
        ),
    ]
