# Generated by Django 5.1.4 on 2025-09-03 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0024_alter_factura_motivo_contingencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='motivo_contingencia',
        ),
    ]
