# Generated by Django 5.1.4 on 2025-09-03 03:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0025_remove_factura_motivo_contingencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contingencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correlativo', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('fecha_inicio', models.DateField()),
                ('hora_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateField()),
                ('hora_fin', models.DateTimeField()),
                ('codigo_generacion', models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='Código de Generación')),
                ('evento_contingencia', models.BooleanField(blank=True, default=False, null=True)),
                ('motivo_contingencia', models.CharField(choices=[('1', 'Sist MH'), ('2', 'Sist Emisor'), ('3', 'Internet'), ('4', 'Eléctrica'), ('5', 'Otra')], default='1', max_length=10, verbose_name='Especifique el motivo de contingencia')),
                ('firma', models.TextField(blank=True, null=True)),
                ('respuesta_firmador', models.TextField(blank=True, null=True)),
                ('respuesta_hacienda', models.TextField(blank=True, null=True)),
                ('fecha_envio', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('estado_envio_hacienda', models.CharField(choices=[('pendiente', 'Pendiente'), ('firmado', 'Firmado'), ('enviado', 'Enviado'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('anulado', 'Anulado')], default='pendiente', max_length=20)),
                ('sello_recepcion', models.CharField(blank=True, max_length=128, null=True)),
                ('version_json', models.CharField(blank=True, max_length=16, null=True)),
                ('facturas_contingencia', models.ManyToManyField(to='facturacion.factura')),
            ],
            options={
                'verbose_name': 'Contingencia',
                'verbose_name_plural': 'Contingencias',
            },
        ),
    ]
