# Generated by Django 5.1.4 on 2025-09-03 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0026_contingencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='contingencia',
            name='idenvio_hacienda',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
