# Generated by Django 5.1.4 on 2025-09-03 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0027_contingencia_idenvio_hacienda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contingencia',
            name='hora_fin',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='contingencia',
            name='hora_inicio',
            field=models.TimeField(),
        ),
    ]
