# Generated by Django 5.1.4 on 2025-09-04 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0028_alter_contingencia_hora_fin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contingencia',
            name='evento_contingencia',
        ),
        migrations.AlterField(
            model_name='factura',
            name='estado_envio_hacienda',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('firmado', 'Firmado'), ('enviado', 'Enviado'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('anulado', 'Anulado'), ('contingencia', 'Contingencia')], default='pendiente', max_length=20),
        ),
    ]
