# Generated by Django 5.1.4 on 2025-09-04 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0029_remove_contingencia_evento_contingencia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='evento_contingencia',
        ),
    ]
