# Generated by Django 5.1.4 on 2025-09-04 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0030_remove_factura_evento_contingencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='detalle_contingencia',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
