# Generated by Django 5.1.4 on 2025-09-04 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0031_factura_detalle_contingencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='fecha_fin_contingencia',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='fecha_inicio_contingencia',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='motivo_contingencia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='tipo_contingencia',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
