# Generated by Django 5.1.4 on 2025-09-05 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0032_factura_fecha_fin_contingencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='estado_envio_hacienda',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('firmado', 'Firmado'), ('enviado', 'Enviado'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('anulado', 'Anulado'), ('contingencia', 'Contingencia'), ('enviado_contingencia', 'Enviado Contingencia')], default='pendiente', max_length=20),
        ),
    ]
