# Generated by Django 5.1.4 on 2025-09-05 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0033_alter_factura_estado_envio_hacienda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contingencia',
            name='fecha_fin',
        ),
        migrations.RemoveField(
            model_name='contingencia',
            name='fecha_inicio',
        ),
        migrations.RemoveField(
            model_name='contingencia',
            name='hora_fin',
        ),
        migrations.RemoveField(
            model_name='contingencia',
            name='hora_inicio',
        ),
        migrations.AddField(
            model_name='contingencia',
            name='detalle_contingencia',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contingencia',
            name='fecha_fin_contingencia',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contingencia',
            name='fecha_inicio_contingencia',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contingencia',
            name='tipo_contingencia',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contingencia',
            name='motivo_contingencia',
            field=models.TextField(blank=True, null=True),
        ),
    ]
