# Generated by Django 5.1.4 on 2025-09-05 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0034_remove_contingencia_fecha_fin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='detalle_contingencia',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='fecha_fin_contingencia',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='fecha_inicio_contingencia',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='motivo_contingencia',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='tipo_contingencia',
        ),
    ]
