# Generated by Django 5.1.4 on 2025-09-05 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0035_remove_factura_detalle_contingencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='detalle_contingencia',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='motivo_contingencia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='tipo_contingencia',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
