# Generated by Django 5.1.4 on 2025-12-29 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documentacion', '0001_initial'),
        ('equipos', '0001_initial'),
        ('proveedores', '0001_initial'),
        ('registros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(default='Descripción de la planificación')),
                ('cantidad_personas', models.PositiveIntegerField()),
                ('horas_estimadas', models.DecimalField(decimal_places=2, max_digits=6)),
                ('equipo_funcionando', models.CharField(choices=[('Si', 'Sí'), ('No', 'No')], default='No', max_length=4)),
                ('horarios_actividad', models.CharField(choices=[('AM', 'Matutino'), ('PM', 'Vespertino'), ('8-5', 'Horario Normal')], default='8-5', max_length=4)),
                ('notas', models.TextField(blank=True)),
                ('documentos_necesarios', models.ManyToManyField(blank=True, to='documentacion.documentacion')),
                ('especialidad', models.ManyToManyField(to='registros.descripcionespuesto')),
                ('herramientas_necesarias', models.ManyToManyField(blank=True, to='equipos.herramienta')),
                ('proveedores', models.ManyToManyField(blank=True, to='proveedores.proveedor')),
            ],
            options={
                'verbose_name_plural': 'Planificaciones',
            },
        ),
    ]
