# Generated by Django 5.1.4 on 2025-04-23 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activos', '0001_initial'),
        ('documentacion', '0003_alter_documentacion_options'),
        ('proveedores', '0005_remove_proveedor_contacto_and_more'),
        ('registros', '0005_remove_descripcionespuesto_porcentaje_comision_and_more'),
        ('servicios', '0004_rename_unidades_unitarias_servicio_descripcion_unidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_personas', models.PositiveIntegerField()),
                ('horas_estimadas', models.DecimalField(decimal_places=2, max_digits=6)),
                ('equipo_funcionando', models.CharField(choices=[('Si', 'Sí'), ('No', 'No')], default='No', max_length=4)),
                ('horarios_actividad', models.DateTimeField()),
                ('notas', models.TextField(blank=True)),
                ('documentos_necesarios', models.ManyToManyField(blank=True, to='documentacion.documentacion')),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registros.descripcionespuesto')),
                ('herramientas_necesarias', models.ManyToManyField(blank=True, to='activos.activo')),
                ('proveedores', models.ManyToManyField(blank=True, to='proveedores.proveedor')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.servicio')),
            ],
        ),
    ]
