# Generated by Django 5.1.4 on 2025-04-23 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0001_initial'),
        ('registros', '0005_remove_descripcionespuesto_porcentaje_comision_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planificacion',
            options={'verbose_name_plural': 'Planificaciones'},
        ),
        migrations.RemoveField(
            model_name='planificacion',
            name='especialidad',
        ),
        migrations.AddField(
            model_name='planificacion',
            name='especialidad',
            field=models.ManyToManyField(to='registros.descripcionespuesto'),
        ),
    ]
