# Generated by Django 5.1.4 on 2025-04-23 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0002_alter_planificacion_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planificacion',
            name='horarios_actividad',
            field=models.CharField(choices=[('AM', 'Matutino'), ('PM', 'Vespertino'), ('8-5', 'Horario Normal')], default='8-5', max_length=4),
        ),
    ]
