# Generated by Django 5.1.4 on 2025-05-07 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0010_herramienta'),
        ('planificacion', '0003_alter_planificacion_horarios_actividad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planificacion',
            name='herramientas_necesarias',
            field=models.ManyToManyField(blank=True, to='equipos.herramienta'),
        ),
    ]
