# Generated by Django 5.1.4 on 2025-05-31 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0004_alter_planificacion_herramientas_necesarias'),
        ('servicios', '0006_rename_precio_unitario_servicio_precio_unitario'),
    ]

    operations = [
        migrations.AddField(
            model_name='planificacion',
            name='descripcion',
            field=models.TextField(default='Descripción de la planificación'),
        ),
        migrations.AlterField(
            model_name='planificacion',
            name='servicio',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='servicios.servicio'),
        ),
    ]
