# Generated by Django 5.1.4 on 2025-05-31 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0005_planificacion_descripcion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planificacion',
            name='servicio',
        ),
    ]
