# Generated by Django 5.1.4 on 2025-05-27 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asientocontable',
            options={'verbose_name': 'Asiento Contable', 'verbose_name_plural': 'Asientos Contables'},
        ),
        migrations.AlterModelOptions(
            name='creditofiscal',
            options={'verbose_name': 'Credito Fiscal', 'verbose_name_plural': 'Creditos Fiscales'},
        ),
        migrations.AlterModelOptions(
            name='declaracionfiscal',
            options={'verbose_name': 'Declaracion fiscal', 'verbose_name_plural': 'Declaraciones fiscales'},
        ),
    ]
