# Generated by Django 5.1.4 on 2026-02-27 00:02

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='categoria',
            field=core.fields.RichTextMediumField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='descripcion',
            field=core.fields.RichTextMediumField(),
        ),
    ]
