# Generated by Django 5.1.4 on 2025-04-15 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reporte',
            old_name='enlace_google_drive',
            new_name='enlace_documento',
        ),
    ]
