"""
Django settings for plataformaSEINS project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from pathlib import Path
from django.urls import reverse_lazy
from decouple import config


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

# SECURITY WARNING: don't run with debug turned on in production!
#DEBUG = False


#ALLOWED_HOSTS = ["seinsv.com", "www.seinsv.com", "3.86.0.104", "127.0.0.1", "localhost"]
ALLOWED_HOSTS = []
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'cotizaciones.apps.CotizacionesConfig',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'clientes',
    'compras',
    'comunicacion',
    'documentacion',
    'equipos',
    'facturacion',
    'indicadores',
    'inventario',
    'planes_mantenimiento',
    'proveedores',
    'proyectos',
    'registros',
    'reportes',
    'usuarios',
    'calendario',
    'actividades',
    'equipos_clientes',
    'servicios',
    'productos',
    #'cotizaciones',
    'recursos_humanos',
    'procesos',
    'activos',
    'finanzas',
    'planificacion',
    'control_calidad',
    'capacitaciones',
    'notificaciones',
    'innovacion',
    'analisis_retroalimentacion',
    'contabilidad',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

CORS_ALLOW_ALL_ORIGINS = True
# o más seguro:
# CORS_ALLOWED_ORIGINS = [
#     "http://localhost:3000",
# ]

ROOT_URLCONF = 'SEINS-ERP.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'notificaciones.context_processors.notificaciones_pendientes',
            ],
        },
    },
]

LOGIN_REDIRECT_URL = '/admin/'
LOGIN_URL = '/admin/login/'
LOGIN_REDIRECT_URL = '/admin/'
LOGOUT_REDIRECT_URL = '/admin/login/'

WSGI_APPLICATION = 'SEINS-ERP.wsgi.application'
# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'es-sv'

TIME_ZONE = 'America/El_Salvador'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

JAZZMIN_SETTINGS = {
    "site_title": "SEINS-ERP Admin",
    "site_header": "Panel Administrativo",
    "site_icon": "img/favicon.png",  
    "site_brand": "SEINS-ERP",
    "site_logo": "img/logo.png",
    "site_logo_classes": "img-circle",
    "topbar_color": "grey",
    "site_logo_height": "15px", 
    "site_logo_width": "auto", 
    "login_background": "img/login.jpg",
    "changeform_format": "horizontal_tabs",
    "show_ui_builder": False,
    "custom_css": "css/custom.css",
    "theme": "dark",
    "welcome_sign": "Administración de SEINS-ERP",
    "copyright": "SEINS S. A. de C. V",
    "search_model": ["actividades.ordendetrabajo", "facturacion.factura", "cotizaciones.cotizacion"],
    "show_sidebar": True,
    "navigation_expanded": True,
    "topmenu_links": [
     {
        "name": "🏠",
        "url": "/admin/",  # o la URL de tu interfaz principal
        "new_window": False,
        "permissions": [],  # Puedes dejarlo vacío si quieres que todos lo vean
     },
     {
        "name": "🔔",
        "url": reverse_lazy("admin:notificaciones_notificacion_changelist"),
        "new_window": False,
        "permissions": ["notificaciones.view_notificacion"],
        "model": "notificaciones.Notificacion",
        "permissions": ["app.view_notificacion"],
        
     },
],

    # Orden alfabético personalizado (ajusta según tus apps reales)
    "order_with_respect_to": [
    "actividades",
    "activos",
    "analisis_retroalimentacion",
    "calendario",
    "capacitaciones",
    "clientes",
    "compras",
    "comunicacion",
    "contabilidad",
    "control_calidad",
    "cotizaciones",
    "documentacion",
    "equipos",
    "equipos_clientes",
    "facturacion",
    "finanzas",
    "indicadores",
    "innovacion",
    "inventario",
    "notificaciones",
    "planes_mantenimiento",
    "planificacion",
    "procesos",
    "productos",
    "proyectos",
    "proveedores",
    "recursos_humanos",
    "registros",
    "reportes",
    "servicios",
    "usuarios"  
    ],
        
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "clientes.cliente": "fas fa-cash-register",
        "clientes.seguimiento": "fas fa-cash-register",
        "actividades.ordendetrabajo": "fas fa-boxes",
        "auth.group": "fas fa-users",
        "calendario.actividade": "fas fa-tasks",
        "compras.compra": "fas fa-shopping-cart",
        "comunicacion.comunicacion": "fas fa-comments",
        "cotizaciones.cotizacion": "fas fa-file-invoice",
        "cotizaciones.detallecotizacionproductos": "fas fa-file-invoice",
        "cotizaciones.detallecotizacionservicios": "fas fa-file-invoice",
        "cotizaciones.listademateriales": "fas fa-file-invoice",
        "documentacion.documentacion": "fas fa-folder-open",
        "equipos.equipo": "fas fa-tools",
        "equipos.herramienta": "fas fa-tools",
        "equipos.historialmantenimiento": "fas fa-tools",
        "facturacion.factura": "fas fa-file-invoice-dollar",
        "facturacion.anulacion": "fas fa-file-invoice-dollar",
        "facturacion.comprobantedonacion": "fas fa-file-invoice-dollar",
        "facturacion.comprobanteretencion": "fas fa-file-invoice-dollar",
        "facturacion.facturasujetoexcluido": "fas fa-file-invoice-dollar",
        "facturacion.notacreditodebito": "fas fa-file-invoice-dollar",
        "facturacion.notaremision": "fas fa-file-invoice-dollar",
        "facturacion.contingencia": "fas fa-file-invoice-dollar",
        "indicadores.indicador": "fas fa-bolt",
        "inventario.inventario": "fas fa-warehouse",
        "planes_mantenimiento.planmantenimiento": "fas fa-calendar-check",
        "planes_mantenimiento.detalleplanmantenimiento": "fas fa-calendar-check",
        "productos.producto": "fas fa-tags",
        "proyectos.proyecto": "fas fa-project-diagram",
        "reportes.reporte": "fas fa-file-alt",
        "servicios.servicio": "fas fa-concierge-bell",
        "equipos_clientes.equipocliente": "fas fa-handshake",
        "equipos_clientes.historialmantenimiento": "fas fa-handshake",
        "proveedores.proveedor": "fas fa-truck",
        "recursos_humanos.empleado": "fa fa-id-card",
        "registros.atestado": "fa fa-clipboard",
        "registros.descripcionespuesto": "fa fa-clipboard",
        "procesos.proceso": "fa fa-cogs",
        "activos.activo": "fa fa-archive",
        "activos.infraestructura": "fa fa-archive",
        "finanzas.gasto": "fa-solid fa-money-bill-wave",
        "finanzas.ingreso": "fa-solid fa-money-bill-wave",
        "finanzas.cuentaporcobrar": "fa-solid fa-money-bill-wave",
        "finanzas.cuentaporpagar": "fa-solid fa-money-bill-wave",
        "finanzas.presupuesto": "fa-solid fa-money-bill-wave",
        "planificacion.planificacion": "fas fa-check-circle",
        "comunicacion.mensajecontacto": "fas fa-comments",
        "comunicacion.notificacion": "fas fa-comments",
        "control_calidad.accioncorrectiva": "fas fa-clipboard-check",
        "control_calidad.auditoria": "fas fa-clipboard-check",
        "control_calidad.noconformidad": "fas fa-clipboard-check",
        "control_calidad.proceso": "fas fa-clipboard-check",
        "capacitaciones.certificado": "fas fa-chalkboard-teacher",
        "capacitaciones.curso": "fas fa-chalkboard-teacher",
        "capacitaciones.empleado": "fas fa-chalkboard-teacher",
        "capacitaciones.inscripcion": "fas fa-chalkboard-teacher",
        "notificaciones.notificacion": "fas fa-bell",
        "innovacion.innovacion": "fas fa-lightbulb",
        "analisis_retroalimentacion.analisis": "fas fa-chart-line",
        "analisis_retroalimentacion.planaccion": "fas fa-chart-line",
        "analisis_retroalimentacion.retroalimentacion": "fas fa-chart-line",
        "contabilidad.asientocontable": "fas fa-book",
        "contabilidad.creditofiscal": "fas fa-book",
        "contabilidad.declaracionfiscal": "fas fa-book",
        "contabilidad.tributo": "fas fa-book",
        
    },
}

JAZZMIN_UI_TWEAKS = {
    "body_small_text": True,
    "brand_small_text": False,
    "accent": "accent-info",
    "navbar": "navbar-dark navbar-primary",
    "no_navbar_border": False,
    "sidebar_nav_small_text": True,
    "footer_small_text": False,
    "body_bg": "bg-dark",  # Esto puede cambiar el fondo general
}


