# Generated by Django 5.1.4 on 2025-05-07 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capacitaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inscripcion',
            options={'verbose_name': 'Inscripcion', 'verbose_name_plural': 'Inscripciones'},
        ),
    ]
