# Generated by Django 5.1.4 on 2025-12-29 20:59

import django.db.models.deletion
import equipos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actividades', '0001_initial'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Herramienta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('categoria', models.CharField(max_length=100)),
                ('cantidad', models.PositiveIntegerField()),
                ('modelo', models.CharField(blank=True, max_length=100)),
                ('serie', models.CharField(blank=True, max_length=100)),
                ('codigo_interno', models.CharField(blank=True, max_length=100)),
                ('marca', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(choices=[('en_uso', 'En uso'), ('fuera_de_uso', 'Fuera de uso'), ('uso_limitado', 'Uso limitado')], default='en_uso', max_length=20)),
                ('componentes', models.PositiveIntegerField(default=1)),
                ('especificaciones', models.CharField(default='especificaciones técnicas de la herramienta', max_length=1000)),
                ('notas', models.TextField(blank=True)),
                ('imagen_herramienta', models.ImageField(blank=True, null=True, upload_to=equipos.models.ruta_imagen_herramienta)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='equipo_interno', max_length=500)),
                ('descripcion', models.CharField(default='equipo de uso en empresa', max_length=1000)),
                ('marca', models.CharField(default='Generico', max_length=100)),
                ('modelo', models.CharField(default='Modelo Generico', max_length=100)),
                ('serie', models.CharField(default='Serie Generica', max_length=100)),
                ('codigo_interno', models.CharField(default='Codigo Interno segun SG', max_length=100)),
                ('ubicacion', models.CharField(default='Ubicación del equipo en la empresa', max_length=1000)),
                ('estatus', models.CharField(default='funcionando', max_length=50)),
                ('categoria', models.CharField(default='General', max_length=100)),
                ('componentes', models.PositiveIntegerField(default=1)),
                ('especificaciones', models.CharField(default='especificaciones técnicas del equipo', max_length=1000)),
                ('notas', models.TextField(blank=True)),
                ('imagen_equipo', models.ImageField(blank=True, null=True, upload_to=equipos.models.ruta_imagen_equipo)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialTrabajos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateField(verbose_name='Fecha de Registro')),
                ('notas', models.TextField(blank=True)),
                ('equipo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='historial_mantenimientos', to='equipos.equipo')),
                ('ordenes_trabajo', models.ManyToManyField(to='actividades.ordendetrabajo')),
            ],
            options={
                'verbose_name': 'Historial de trabajo',
                'verbose_name_plural': 'Historial de trabajos',
            },
        ),
    ]
