# Generated by Django 5.1.4 on 2026-01-23 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='especificaciones',
            field=models.TextField(default='especificaciones técnicas del equipo', max_length=1000),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='ubicacion',
            field=models.TextField(default='Ubicación del equipo en la empresa', max_length=1000),
        ),
        migrations.AlterField(
            model_name='herramienta',
            name='especificaciones',
            field=models.TextField(default='especificaciones técnicas de la herramienta', max_length=1000),
        ),
    ]
