# Generated by Django 5.1.4 on 2026-02-27 00:02

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0002_alter_equipo_especificaciones_alter_equipo_ubicacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='categoria',
            field=core.fields.RichTextSimpleField(default='General', max_length=100),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='descripcion',
            field=core.fields.RichTextSimpleField(default='equipo de uso en empresa', max_length=1000),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='especificaciones',
            field=core.fields.RichTextSimpleField(default='especificaciones técnicas del equipo', max_length=1000),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='notas',
            field=core.fields.RichTextSimpleField(blank=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='ubicacion',
            field=core.fields.RichTextSimpleField(default='Ubicación del equipo en la empresa', max_length=1000),
        ),
        migrations.AlterField(
            model_name='herramienta',
            name='categoria',
            field=core.fields.RichTextSimpleField(max_length=100),
        ),
        migrations.AlterField(
            model_name='herramienta',
            name='descripcion',
            field=core.fields.RichTextSimpleField(blank=True),
        ),
        migrations.AlterField(
            model_name='herramienta',
            name='especificaciones',
            field=core.fields.RichTextSimpleField(default='especificaciones técnicas de la herramienta', max_length=1000),
        ),
        migrations.AlterField(
            model_name='herramienta',
            name='marca',
            field=core.fields.RichTextSimpleField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='herramienta',
            name='modelo',
            field=core.fields.RichTextSimpleField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='herramienta',
            name='notas',
            field=core.fields.RichTextSimpleField(blank=True),
        ),
        migrations.AlterField(
            model_name='herramienta',
            name='serie',
            field=core.fields.RichTextSimpleField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='historialtrabajos',
            name='notas',
            field=core.fields.RichTextSimpleField(blank=True),
        ),
    ]
