# Generated by Django 5.1.4 on 2025-04-20 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0002_remove_equipo_creado_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='codigo_interno',
            field=models.CharField(default='Codigo Interno segun SG', max_length=100),
        ),
    ]
