# Generated by Django 5.1.4 on 2026-03-20 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0003_alter_equipo_categoria_alter_equipo_descripcion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herramienta',
            name='serie',
        ),
    ]
