# Generated by Django 5.1.4 on 2025-04-22 20:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0003_equipo_codigo_interno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialmantenimiento',
            name='fecha_mant',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha del Mantenimiento'),
        ),
    ]
