# Generated by Django 5.1.4 on 2026-03-27 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0004_remove_herramienta_serie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='categoria',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AlterField(
            model_name='herramienta',
            name='categoria',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='herramienta',
            name='marca',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='herramienta',
            name='modelo',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
