# Generated by Django 5.1.4 on 2025-04-22 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0004_alter_historialmantenimiento_fecha_mant'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialmantenimiento',
            name='costo_repuestos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='historialmantenimiento',
            name='costo_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
