# Generated by Django 5.1.4 on 2026-05-08 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0005_alter_equipo_categoria_alter_herramienta_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='descripcion',
            field=models.TextField(default='equipo de uso en empresa', max_length=1000),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='ubicacion',
            field=models.TextField(default='Ubicación del equipo en la empresa', max_length=1000),
        ),
        migrations.AlterField(
            model_name='herramienta',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
    ]
