# Generated by Django 5.1.4 on 2025-04-22 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0005_historialmantenimiento_costo_repuestos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='costo_total_acumulado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
