# Generated by Django 5.1.4 on 2025-04-22 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0006_equipo_costo_total_acumulado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='costo_total_acumulado',
        ),
    ]
