# Generated by Django 5.1.4 on 2025-04-22 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0007_remove_equipo_costo_total_acumulado'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialmantenimiento',
            name='indicacion_odometro',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='historialmantenimiento',
            name='unidad_odometro',
            field=models.CharField(choices=[('M', 'Millas'), ('Km', 'Kilometros'), ('Hr', 'Horas'), ('%', 'Porcentaje')], default='Km', max_length=4),
        ),
    ]
