# Generated by Django 5.1.4 on 2025-04-23 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0008_historialmantenimiento_indicacion_odometro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialmantenimiento',
            name='indicacion_odometro',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
