# Generated by Django 5.1.4 on 2025-05-07 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0009_alter_historialmantenimiento_indicacion_odometro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Herramienta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('categoria', models.CharField(max_length=100)),
                ('cantidad', models.PositiveIntegerField()),
                ('modelo', models.CharField(blank=True, max_length=100)),
                ('serie', models.CharField(blank=True, max_length=100)),
                ('codigo_interno', models.CharField(blank=True, max_length=100)),
                ('marca', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(choices=[('en_uso', 'En uso'), ('fuera_de_uso', 'Fuera de uso'), ('uso_limitado', 'Uso limitado')], default='en_uso', max_length=20)),
                ('notas', models.TextField(blank=True)),
            ],
        ),
    ]
