# Generated by Django 5.1.4 on 2025-11-27 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0010_herramienta'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='ubicación',
            field=models.CharField(default='Ubicación del equipo en la empresa', max_length=100),
        ),
    ]
