# Generated by Django 5.1.4 on 2025-12-01 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0030_remove_ordendetrabajo_firma_tecnico_and_more'),
        ('equipos', '0011_equipo_ubicación'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='notas',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='equipo',
            name='ordenes_trabajo',
            field=models.ManyToManyField(to='actividades.ordendetrabajo'),
        ),
        migrations.DeleteModel(
            name='HistorialMantenimiento',
        ),
    ]
