# Generated by Django 5.1.4 on 2025-12-01 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0030_remove_ordendetrabajo_firma_tecnico_and_more'),
        ('equipos', '0012_equipo_notas_equipo_ordenes_trabajo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='ordenes_trabajo',
        ),
        migrations.CreateModel(
            name='HistorialTrabajos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notas', models.TextField(blank=True)),
                ('ordenes_trabajo', models.ManyToManyField(to='actividades.ordendetrabajo')),
            ],
        ),
    ]
