# Generated by Django 5.1.4 on 2025-12-01 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0013_remove_equipo_ordenes_trabajo_historialtrabajos'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialtrabajos',
            name='equipo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='historial_mantenimientos', to='equipos.equipo'),
        ),
    ]
