# Generated by Django 5.1.4 on 2025-12-01 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0014_historialtrabajos_equipo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historialtrabajos',
            options={'verbose_name': 'Histrorial de trabajo', 'verbose_name_plural': 'Histrorial de trabajos'},
        ),
    ]
