# Generated by Django 5.1.4 on 2025-12-01 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0015_alter_historialtrabajos_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historialtrabajos',
            options={'verbose_name': 'Historial de trabajo', 'verbose_name_plural': 'Historial de trabajos'},
        ),
    ]
