# Generated by Django 5.1.4 on 2025-12-01 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0016_alter_historialtrabajos_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipo',
            old_name='ubicación',
            new_name='ubicacion',
        ),
    ]
