# Generated by Django 5.1.4 on 2025-12-01 23:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0017_rename_ubicación_equipo_ubicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialtrabajos',
            name='fecha_registro',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de Registro'),
            preserve_default=False,
        ),
    ]
