# Generated by Django 5.1.4 on 2025-12-01 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0018_historialtrabajos_fecha_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialtrabajos',
            name='fecha_registro',
            field=models.DateField(verbose_name='Fecha de Registro'),
        ),
    ]
