# Generated by Django 5.1.4 on 2025-12-28 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0026_cliente_correlativo'),
        ('equipos', '0019_alter_historialtrabajos_fecha_registro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='cantidad',
        ),
        migrations.AddField(
            model_name='equipo',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='componentes',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='equipo',
            name='especificaciones',
            field=models.CharField(default='especificaciones técnicas del equipo', max_length=1000),
        ),
        migrations.AddField(
            model_name='herramienta',
            name='componentes',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='herramienta',
            name='especificaciones',
            field=models.CharField(default='especificaciones técnicas de la herramienta', max_length=1000),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='descripcion',
            field=models.CharField(default='equipo de uso en empresa', max_length=1000),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='nombre',
            field=models.CharField(default='equipo_interno', max_length=500),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='ubicacion',
            field=models.CharField(default='Ubicación del equipo en la empresa', max_length=1000),
        ),
    ]
