# Generated by Django 5.1.4 on 2025-12-29 00:06

import equipos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0020_remove_equipo_cantidad_equipo_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='imagen_equipo',
            field=models.ImageField(blank=True, null=True, upload_to=equipos.models.ruta_imagen_equipo),
        ),
        migrations.AddField(
            model_name='herramienta',
            name='imagen_herramienta',
            field=models.ImageField(blank=True, null=True, upload_to=equipos.models.ruta_imagen_herramienta),
        ),
    ]
