# Generated by Django 5.1.4 on 2025-02-07 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('categoria', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('serie', models.CharField(max_length=100, unique=True)),
                ('modelo', models.CharField(max_length=100)),
                ('existencia', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
