# Generated by Django 5.1.4 on 2025-12-29 20:59

import django.db.models.deletion
import productos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipos', '0001_initial'),
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('correlativo', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('nombre', models.CharField(default='Nombre del Producto', max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, default='Descripción del Producto', null=True)),
                ('categoria', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('serie', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('existencia', models.TextField(choices=[('EN STOCK', 'en stock'), ('SIN STOCK', 'sin stock')], default='EN STOCK')),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0.0, help_text='Colocar precios sin IVA', max_digits=10)),
                ('factura_compra', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_compra', models.DateField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('imagen_producto', models.ImageField(blank=True, null=True, upload_to=productos.models.ruta_imagen_producto)),
                ('equipo', models.ManyToManyField(blank=True, to='equipos.equipo')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proveedores.proveedor')),
            ],
        ),
    ]
