# Generated by Django 5.1.4 on 2026-02-27 00:02

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=core.fields.RichTextMediumField(max_length=100),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=core.fields.RichTextMediumField(blank=True, default='Descripción del Producto', null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='marca',
            field=core.fields.RichTextMediumField(max_length=100),
        ),
        migrations.AlterField(
            model_name='producto',
            name='modelo',
            field=core.fields.RichTextMediumField(max_length=100),
        ),
        migrations.AlterField(
            model_name='producto',
            name='notas',
            field=core.fields.RichTextMediumField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='serie',
            field=core.fields.RichTextMediumField(max_length=100),
        ),
    ]
