# Generated by Django 5.1.4 on 2025-06-08 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_producto_preciounitario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='PrecioUnitario',
            new_name='precio_unitario',
        ),
    ]
