# Generated by Django 5.1.4 on 2025-06-08 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_rename_preciounitario_producto_precio_unitario'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, default='Descripción del Producto', null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='nombre',
            field=models.CharField(default='Nombre del Producto', max_length=100, unique=True),
        ),
    ]
