# Generated by Django 5.1.4 on 2025-06-13 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_producto_descripcion_producto_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='correlativo',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
