# Generated by Django 5.1.4 on 2025-08-29 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_producto_correlativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='existencia',
            field=models.PositiveIntegerField(choices=[('EN STOCK', 'en stock'), ('SIN STOCK', 'sin stock')], default='EN STOCK'),
        ),
    ]
