# Generated by Django 5.1.4 on 2025-08-29 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_alter_producto_existencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='existencia',
            field=models.TextField(choices=[('EN STOCK', 'en stock'), ('SIN STOCK', 'sin stock')], default='EN STOCK'),
        ),
    ]
