# Generated by Django 5.1.4 on 2025-09-28 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_alter_producto_existencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Colocar precios sin IVA', max_digits=10),
        ),
    ]
