# Generated by Django 5.1.4 on 2025-10-02 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_alter_producto_precio_unitario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='serie',
            field=models.CharField(max_length=100),
        ),
    ]
