# Generated by Django 5.1.4 on 2025-12-28 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0019_alter_historialtrabajos_fecha_registro'),
        ('productos', '0009_alter_producto_serie'),
        ('proveedores', '0010_proveedor_correlativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='equipo',
            field=models.ManyToManyField(blank=True, to='equipos.equipo'),
        ),
        migrations.AddField(
            model_name='producto',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proveedores.proveedor'),
        ),
    ]
