# Generated by Django 5.1.4 on 2025-12-28 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0010_producto_equipo_producto_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='factura_compra',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_compra',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='notas',
            field=models.TextField(blank=True, null=True),
        ),
    ]
