# Generated by Django 5.1.4 on 2025-12-29 05:56

import productos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0011_producto_factura_compra_producto_fecha_compra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen_producto',
            field=models.ImageField(blank=True, null=True, upload_to=productos.models.ruta_imagen_producto),
        ),
    ]
