# Generated by Django 5.1.4 on 2025-02-06 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_empresa', models.CharField(max_length=255, unique=True)),
                ('direccion', models.TextField()),
                ('telefono_contacto', models.CharField(max_length=15)),
                ('sub_area', models.CharField(max_length=100)),
                ('nombre_contacto', models.CharField(max_length=255)),
            ],
        ),
    ]
