# Generated by Django 5.1.4 on 2025-12-29 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('cotizaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seguimiento',
            name='cotizaciones',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='historial_cotizaciones', to='cotizaciones.cotizacion'),
        ),
    ]
