# Generated by Django 5.1.4 on 2025-02-08 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='correo',
            field=models.CharField(default='ejemplo@midominio.com', max_length=100),
        ),
    ]
