# Generated by Django 5.1.4 on 2026-02-27 00:02

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=core.fields.RichTextMediumField(),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='sub_area',
            field=core.fields.RichTextMediumField(max_length=100),
        ),
    ]
