# Generated by Django 5.1.4 on 2025-05-07 00:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_correo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_contacto', models.DateField(default=django.utils.timezone.now)),
                ('medio_contacto', models.CharField(choices=[('email', 'Correo electrónico'), ('telefono', 'Teléfono'), ('visita', 'Visita presencial'), ('otro', 'Otro')], max_length=100)),
                ('asunto', models.CharField(max_length=200)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('proxima_accion', models.TextField(blank=True, null=True)),
                ('fecha_proxima_contacto', models.DateField(blank=True, null=True)),
                ('responsable', models.CharField(max_length=255)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='clientes.cliente')),
            ],
        ),
    ]
