# Generated by Django 5.1.4 on 2026-03-27 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_alter_cliente_direccion_alter_cliente_sub_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='sub_area',
            field=models.CharField(max_length=100),
        ),
    ]
