# Generated by Django 5.1.4 on 2025-05-09 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_seguimiento'),
        ('cotizaciones', '0003_alter_cotizacion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seguimiento',
            name='cotizaciones',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='historial_cotizaciones', to='cotizaciones.cotizacion'),
        ),
    ]
