# Generated by Django 5.1.4 on 2025-05-09 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_seguimiento_cotizaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='seguimiento',
            name='estado_cotizacion',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20),
        ),
    ]
