# Generated by Django 5.1.4 on 2025-06-07 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_seguimiento_estado_cotizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='nit',
            field=models.CharField(default='0000000000', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nrc',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo_cliente',
            field=models.CharField(choices=[('persona_natural', 'Persona Natural'), ('persona_juridica', 'Persona Jurídica')], default='persona_natural', max_length=20),
        ),
    ]
