# Generated by Django 5.1.4 on 2025-06-08 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_cliente_nit_cliente_nrc_cliente_tipo_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='departamento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='municipio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
