# Generated by Django 5.1.4 on 2025-07-09 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_cliente_departamento_cliente_municipio'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='actividad_economica',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
