# Generated by Django 5.1.4 on 2025-07-09 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_cliente_actividad_economica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='actividad_economica',
            field=models.CharField(blank=True, default='N/A', max_length=100),
        ),
    ]
