# Generated by Django 5.1.4 on 2025-07-13 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_alter_cliente_actividad_economica'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='actividad_codigo',
            field=models.CharField(blank=True, default='9999', max_length=4),
        ),
    ]
