# Generated by Django 5.1.4 on 2025-07-13 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0011_alter_cliente_actividad_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='actividad_codigo',
            field=models.CharField(blank=True, default='99999', max_length=5),
        ),
    ]
