# Generated by Django 5.1.4 on 2025-07-16 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0012_alter_cliente_actividad_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='municipio',
            field=models.CharField(choices=[('00', 'Otros (Extranjeros)'), ('01', 'Ahuachapán'), ('02', 'Santa Ana'), ('03', 'Sonsonate'), ('04', 'Chalatenango'), ('05', 'La Libertad'), ('06', 'San Salvador'), ('07', 'Cuscatlán'), ('08', 'La Paz'), ('09', 'Cabañas'), ('10', 'San Vicente'), ('11', 'Usulután'), ('12', 'San Miguel'), ('13', 'Morazán'), ('14', 'La Unión')], default='06', help_text='Seleccione el municipio donde se ubica el cliente', max_length=2, verbose_name='Municipio'),
        ),
    ]
