# Generated by Django 5.1.4 on 2025-07-17 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0014_alter_cliente_departamento_alter_cliente_municipio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='municipio',
            field=models.CharField(choices=[('00', 'Otros (extranjeros)'), ('13', 'Ahuachapán Norte'), ('14', 'Ahuachapán Centro'), ('15', 'Ahuachapán Sur'), ('14', 'Santa Ana Norte'), ('15', 'Santa Ana Centro'), ('16', 'Santa Ana Este'), ('17', 'Santa Ana Oeste'), ('17', 'Sonsonate Norte'), ('18', 'Sonsonate Centro'), ('19', 'Sonsonate Este'), ('20', 'Sonsonate Oeste'), ('34', 'Chalatenango Norte'), ('35', 'Chalatenango Centro'), ('36', 'Chalatenango Sur'), ('23', 'La Libertad Norte'), ('24', 'La Libertad Centro'), ('25', 'La Libertad Oeste'), ('26', 'La Libertad Este'), ('27', 'La Libertad Costa'), ('28', 'La Libertad Sur'), ('20', 'San Salvador Norte'), ('21', 'San Salvador Oeste'), ('22', 'San Salvador Este'), ('23', 'San Salvador Centro'), ('24', 'San Salvador Sur'), ('17', 'Cuscatlán Norte'), ('18', 'Cuscatlán Sur'), ('23', 'La Paz Oeste'), ('24', 'La Paz Centro'), ('25', 'La Paz Este'), ('10', 'Cabañas Oeste'), ('11', 'Cabañas Este'), ('14', 'San Vicente Norte'), ('15', 'San Vicente Sur'), ('24', 'Usulután Norte'), ('25', 'Usulután Este'), ('26', 'Usulután Oeste'), ('21', 'San Miguel Norte'), ('22', 'San Miguel Centro'), ('23', 'San Miguel Oeste'), ('27', 'Morazán Norte'), ('28', 'Morazán Sur'), ('19', 'La Unión Norte'), ('20', 'La Unión Sur')], default='00', max_length=3, verbose_name='Municipio'),
        ),
    ]
