# Generated by Django 5.1.4 on 2025-07-18 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0020_alter_cliente_actividad_codigo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='actividad_descripcion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción de la Actividad Económica'),
        ),
    ]
