# Generated by Django 5.1.4 on 2025-07-18 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0021_cliente_actividad_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='nit',
            field=models.CharField(default='0000000000', help_text='Numero son guiones ni espacios', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nrc',
            field=models.CharField(blank=True, help_text='Numero son guiones ni espacios', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono_contacto',
            field=models.CharField(help_text='Numero son guiones ni espacios', max_length=15),
        ),
    ]
