# Generated by Django 5.1.4 on 2025-07-25 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0022_alter_cliente_nit_alter_cliente_nrc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='agente_retencion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cliente',
            name='aplica_descuento',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cliente',
            name='retencion_renta',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nit',
            field=models.CharField(default='0000000000', help_text='Numero sin guiones ni espacios', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nrc',
            field=models.CharField(blank=True, help_text='Numero sin guiones ni espacios', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono_contacto',
            field=models.CharField(help_text='Numero sin guiones ni espacios', max_length=15),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo_cliente',
            field=models.CharField(choices=[('gobierno', 'Gobierno central'), ('alcaldia', 'Alcaldía'), ('autonoma', 'Institución autónoma'), ('persona_juridica', 'Persona Juridica'), ('persona_natural', 'Persona natural'), ('excluido', 'Contribuyente excluido')], max_length=50),
        ),
    ]
