# Generated by Django 5.1.4 on 2025-08-09 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0023_cliente_agente_retencion_cliente_aplica_descuento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='agente_retencion',
            new_name='sujeto_excluido',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='retencion_renta',
        ),
    ]
