# Generated by Django 5.1.4 on 2025-08-13 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0024_rename_agente_retencion_cliente_sujeto_excluido_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='aplica_descuento',
            new_name='aplica_retencion',
        ),
    ]
