# Generated by Django 5.1.4 on 2025-09-12 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0025_rename_aplica_descuento_cliente_aplica_retencion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='correlativo',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
