# Generated by Django 5.1.4 on 2025-04-18 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable_entrada_1', models.FloatField()),
                ('unidades_variable_1', models.CharField(max_length=50)),
                ('variable_entrada_2', models.FloatField()),
                ('unidades_variable_2', models.CharField(max_length=50)),
                ('variable_entrada_3', models.FloatField()),
                ('unidades_variable_3', models.CharField(max_length=50)),
                ('variable_entrada_4', models.FloatField()),
                ('unidades_variable_4', models.CharField(max_length=50)),
                ('variable_entrada_5', models.FloatField()),
                ('unidades_variable_5', models.CharField(max_length=50)),
                ('formula_proceso', models.TextField()),
                ('resultado_1', models.FloatField()),
                ('unidades_resultado_1', models.CharField(max_length=50)),
                ('resultado_2', models.FloatField()),
                ('unidades_resultado_2', models.CharField(max_length=50)),
            ],
        ),
    ]
