# Generated by Django 5.1.4 on 2025-12-29 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_del_proceso', models.CharField(default='nombre o descripción breve del proceso', max_length=200)),
                ('nombre_variable_1', models.CharField(default='variable 1', max_length=50)),
                ('variable_entrada_1', models.FloatField(default=0)),
                ('unidades_variable_1', models.CharField(max_length=25)),
                ('nombre_variable_2', models.CharField(blank=True, default='variable 2', max_length=50)),
                ('variable_entrada_2', models.FloatField(blank=True, default=0)),
                ('unidades_variable_2', models.CharField(blank=True, max_length=25)),
                ('nombre_variable_3', models.CharField(blank=True, default='variable 3', max_length=50)),
                ('variable_entrada_3', models.FloatField(blank=True, default=0)),
                ('unidades_variable_3', models.CharField(blank=True, max_length=25)),
                ('nombre_variable_4', models.CharField(blank=True, default='variable 4', max_length=50)),
                ('variable_entrada_4', models.FloatField(blank=True, default=0)),
                ('unidades_variable_4', models.CharField(blank=True, max_length=25)),
                ('nombre_variable_5', models.CharField(blank=True, default='variable 5', max_length=50)),
                ('variable_entrada_5', models.FloatField(blank=True, default=0)),
                ('unidades_variable_5', models.CharField(blank=True, max_length=25)),
                ('nombre_variable_6', models.CharField(blank=True, default='variable 6', max_length=50)),
                ('variable_entrada_6', models.FloatField(blank=True, default=0)),
                ('unidades_variable_6', models.CharField(blank=True, max_length=25)),
                ('nombre_variable_7', models.CharField(blank=True, default='variable 7', max_length=50)),
                ('variable_entrada_7', models.FloatField(blank=True, default=0)),
                ('unidades_variable_7', models.CharField(blank=True, max_length=25)),
                ('nombre_variable_8', models.CharField(blank=True, default='variable 8', max_length=50)),
                ('variable_entrada_8', models.FloatField(blank=True, default=0)),
                ('unidades_variable_8', models.CharField(blank=True, max_length=25)),
                ('nombre_variable_9', models.CharField(blank=True, default='variable 9', max_length=50)),
                ('variable_entrada_9', models.FloatField(blank=True, default=0)),
                ('unidades_variable_9', models.CharField(blank=True, max_length=25)),
                ('nombre_variable_10', models.CharField(blank=True, default='variable 10', max_length=50)),
                ('variable_entrada_10', models.FloatField(blank=True, default=0)),
                ('unidades_variable_10', models.CharField(blank=True, max_length=25)),
                ('formula_proceso', models.TextField(help_text="Escribe una fórmula usando v1, v2, ..., v10. No uses '=' ni 'R1 ='. Solo la expresión.")),
                ('nombre_resultado', models.CharField(blank=True, max_length=50)),
                ('resultado', models.FloatField(blank=True, null=True)),
                ('unidades_resultado', models.CharField(blank=True, max_length=25)),
            ],
        ),
    ]
