# Generated by Django 5.1.4 on 2025-04-18 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proceso',
            name='formula_proceso',
            field=models.TextField(help_text='Usa v1, v2, v3, v4, v5 como nombres de las variables.'),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='resultado_1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='resultado_2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='unidades_resultado_1',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='unidades_resultado_2',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
