# Generated by Django 5.1.4 on 2025-04-18 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0002_alter_proceso_formula_proceso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proceso',
            name='nombre_del_proceso',
            field=models.CharField(default='nombre o descripción breve del proceso', max_length=200),
        ),
    ]
