# Generated by Django 5.1.4 on 2025-04-18 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0003_proceso_nombre_del_proceso'),
    ]

    operations = [
        migrations.AddField(
            model_name='proceso',
            name='nombre_resultado_1',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='proceso',
            name='nombre_resultado_2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='proceso',
            name='nombre_variable_1',
            field=models.CharField(default='variable 1', max_length=50),
        ),
        migrations.AddField(
            model_name='proceso',
            name='nombre_variable_2',
            field=models.CharField(default='variable 2', max_length=50),
        ),
        migrations.AddField(
            model_name='proceso',
            name='nombre_variable_3',
            field=models.CharField(default='variable 3', max_length=50),
        ),
        migrations.AddField(
            model_name='proceso',
            name='nombre_variable_4',
            field=models.CharField(default='variable 4', max_length=50),
        ),
        migrations.AddField(
            model_name='proceso',
            name='nombre_variable_5',
            field=models.CharField(default='variable 5', max_length=50),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='unidades_resultado_1',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='unidades_resultado_2',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='unidades_variable_1',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='unidades_variable_2',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='unidades_variable_3',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='unidades_variable_4',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='unidades_variable_5',
            field=models.CharField(max_length=25),
        ),
    ]
