# Generated by Django 5.1.4 on 2025-04-22 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0004_proceso_nombre_resultado_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proceso',
            name='nombre_variable_10',
            field=models.CharField(default='variable 10', max_length=50),
        ),
        migrations.AddField(
            model_name='proceso',
            name='nombre_variable_6',
            field=models.CharField(default='variable 6', max_length=50),
        ),
        migrations.AddField(
            model_name='proceso',
            name='nombre_variable_7',
            field=models.CharField(default='variable 7', max_length=50),
        ),
        migrations.AddField(
            model_name='proceso',
            name='nombre_variable_8',
            field=models.CharField(default='variable 8', max_length=50),
        ),
        migrations.AddField(
            model_name='proceso',
            name='nombre_variable_9',
            field=models.CharField(default='variable 9', max_length=50),
        ),
        migrations.AddField(
            model_name='proceso',
            name='unidades_variable_10',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='proceso',
            name='unidades_variable_6',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='proceso',
            name='unidades_variable_7',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='proceso',
            name='unidades_variable_8',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='proceso',
            name='unidades_variable_9',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='proceso',
            name='variable_entrada_10',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='proceso',
            name='variable_entrada_6',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='proceso',
            name='variable_entrada_7',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='proceso',
            name='variable_entrada_8',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='proceso',
            name='variable_entrada_9',
            field=models.FloatField(default=0),
        ),
    ]
