# Generated by Django 5.1.4 on 2025-04-22 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0005_proceso_nombre_variable_10_proceso_nombre_variable_6_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proceso',
            name='nombre_variable_10',
            field=models.CharField(blank=True, default='variable 10', max_length=50),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='nombre_variable_2',
            field=models.CharField(blank=True, default='variable 2', max_length=50),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='nombre_variable_3',
            field=models.CharField(blank=True, default='variable 3', max_length=50),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='nombre_variable_4',
            field=models.CharField(blank=True, default='variable 4', max_length=50),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='nombre_variable_5',
            field=models.CharField(blank=True, default='variable 5', max_length=50),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='nombre_variable_6',
            field=models.CharField(blank=True, default='variable 6', max_length=50),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='nombre_variable_7',
            field=models.CharField(blank=True, default='variable 7', max_length=50),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='nombre_variable_8',
            field=models.CharField(blank=True, default='variable 8', max_length=50),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='nombre_variable_9',
            field=models.CharField(blank=True, default='variable 9', max_length=50),
        ),
    ]
