# Generated by Django 5.1.4 on 2025-04-22 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0006_alter_proceso_nombre_variable_10_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proceso',
            name='variable_entrada_1',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='variable_entrada_2',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='variable_entrada_3',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='variable_entrada_4',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='variable_entrada_5',
            field=models.FloatField(default=0),
        ),
    ]
