# Generated by Django 5.1.4 on 2025-04-22 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0007_alter_proceso_variable_entrada_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proceso',
            name='variable_entrada_10',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='variable_entrada_2',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='variable_entrada_3',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='variable_entrada_4',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='variable_entrada_5',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='variable_entrada_6',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='variable_entrada_7',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='variable_entrada_8',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='variable_entrada_9',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
