# Generated by Django 5.1.4 on 2025-04-22 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0008_alter_proceso_variable_entrada_10_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proceso',
            name='unidades_variable_2',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='unidades_variable_3',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='unidades_variable_4',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='unidades_variable_5',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
