# Generated by Django 5.1.4 on 2025-04-23 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0009_alter_proceso_unidades_variable_2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proceso',
            old_name='nombre_resultado_1',
            new_name='nombre_resultado',
        ),
        migrations.RenameField(
            model_name='proceso',
            old_name='resultado_1',
            new_name='resultado',
        ),
        migrations.RenameField(
            model_name='proceso',
            old_name='unidades_resultado_1',
            new_name='unidades_resultado',
        ),
        migrations.RemoveField(
            model_name='proceso',
            name='nombre_resultado_2',
        ),
        migrations.RemoveField(
            model_name='proceso',
            name='resultado_2',
        ),
        migrations.RemoveField(
            model_name='proceso',
            name='unidades_resultado_2',
        ),
    ]
