# Generated by Django 5.1.4 on 2025-04-23 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0010_rename_nombre_resultado_1_proceso_nombre_resultado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proceso',
            name='formula_proceso',
            field=models.TextField(help_text="Escribe una fórmula usando v1, v2, ..., v10. No uses '=' ni 'R1 ='. Solo la expresión."),
        ),
    ]
