# Generated by Django 5.1.4 on 2025-12-29 20:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('equipos', '0001_initial'),
        ('productos', '0001_initial'),
        ('servicios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correlativo', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('Descripcion', models.TextField(default='Descripcion de la cotización')),
                ('porcentaje_administracion', models.DecimalField(decimal_places=0, default=0, max_digits=5)),
                ('porcentaje_ganancia', models.DecimalField(decimal_places=0, default=0, max_digits=5)),
                ('validez_oferta', models.PositiveIntegerField(default=15)),
                ('unidades_oferta', models.CharField(default='dias', max_length=50)),
                ('condiciones_pago', models.CharField(choices=[('Contado', 'Contado'), ('Credito', 'Crédito'), ('Otros', 'Otros')], default=None, max_length=20, verbose_name='Condición de Operación')),
                ('dias_credito', models.PositiveIntegerField(default=0, help_text='Días de crédito otorgado')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('total_iva', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('estatus', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('no_aprobada', 'No aprobada')], default='pendiente', max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('equipo', models.ManyToManyField(blank=True, to='equipos.equipo')),
                ('usuario', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cotizacion',
                'verbose_name_plural': 'Cotizaciones',
            },
        ),
        migrations.CreateModel(
            name='DetalleCotizacionProductos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('unidades_cantidad', models.CharField(default='Unidad', max_length=50)),
                ('subtotal', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_productos', to='cotizaciones.cotizacion')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.producto')),
            ],
            options={
                'verbose_name': 'Cotizacion de Producto',
                'verbose_name_plural': 'Cotizacion de Productos',
            },
        ),
        migrations.CreateModel(
            name='DetalleCotizacionServicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('unidades_cantidad', models.CharField(default='Unidad', max_length=50)),
                ('precio_unitario', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_servicios', to='cotizaciones.cotizacion')),
                ('servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicios.servicio')),
            ],
            options={
                'verbose_name': 'Cotizacion de Servicio',
                'verbose_name_plural': 'Cotizacion de Servicios',
            },
        ),
        migrations.CreateModel(
            name='ListaDeMateriales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_material', models.TextField(blank=True, null=True)),
                ('cantidad', models.DecimalField(blank=True, decimal_places=0, default=1.0, max_digits=10)),
                ('unidades', models.CharField(blank=True, default='Unidad', max_length=100)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lista_materiales', to='cotizaciones.cotizacion')),
            ],
            options={
                'verbose_name': 'Lista de Materiales',
                'verbose_name_plural': 'Listas de Materiales',
            },
        ),
    ]
