# Generated by Django 5.1.4 on 2026-02-26 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='porcentaje_administracion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='porcentaje_ganancia',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
