# Generated by Django 5.1.4 on 2025-04-22 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0002_detallecotizacionproductos_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cotizacion',
            options={'verbose_name': 'Cotizacion', 'verbose_name_plural': 'Cotizaciones'},
        ),
        migrations.AlterModelOptions(
            name='detallecotizacionproductos',
            options={'verbose_name': 'Cotizacion de Producto', 'verbose_name_plural': 'Cotizacion de Productos'},
        ),
        migrations.AlterModelOptions(
            name='detallecotizacionservicios',
            options={'verbose_name': 'Cotizacion de Servicio', 'verbose_name_plural': 'Cotizacion de Servicios'},
        ),
    ]
