# Generated by Django 5.1.4 on 2026-02-27 00:02

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0002_alter_cotizacion_porcentaje_administracion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='Descripcion',
            field=core.fields.RichTextMediumField(default='Descripcion de la cotización'),
        ),
    ]
