# Generated by Django 5.1.4 on 2025-05-29 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0003_alter_cotizacion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='Cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='Descripcion',
            field=models.TextField(default='Descripcion de la cotización'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='porcentaje_administracion',
            field=models.DecimalField(decimal_places=0, default=15, max_digits=5),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='porcentaje_ganacia',
            field=models.DecimalField(decimal_places=0, default=15, max_digits=5),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='validez_oferta',
            field=models.PositiveIntegerField(default=15),
        ),
    ]
