# Generated by Django 5.1.4 on 2025-05-29 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0004_cotizacion_cantidad_cotizacion_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='condiciones_pago',
            field=models.TextField(default='Condiciones de pago'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='unidades_oferta',
            field=models.CharField(default='dias', max_length=50),
        ),
    ]
