# Generated by Django 5.1.4 on 2025-05-29 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0005_cotizacion_condiciones_pago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallecotizacionservicios',
            name='unidades_cantidad',
            field=models.CharField(default='Unidad', max_length=50),
        ),
    ]
