# Generated by Django 5.1.4 on 2025-05-29 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0006_detallecotizacionservicios_unidades_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='total',
            field=models.DecimalField(decimal_places=0, default=0.0, max_digits=10),
        ),
    ]
