# Generated by Django 5.1.4 on 2025-05-29 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0007_alter_cotizacion_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='dias_credito',
            field=models.PositiveIntegerField(default=0, help_text='Días de crédito otorgado'),
        ),
    ]
