# Generated by Django 5.1.4 on 2025-05-29 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0008_cotizacion_dias_credito'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='estatus',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('no_aprobada', 'No aprobada')], default='pendiente', max_length=20),
        ),
    ]
