# Generated by Django 5.1.4 on 2025-05-31 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0009_cotizacion_estatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cotizacion',
            old_name='porcentaje_ganacia',
            new_name='porcentaje_ganancia',
        ),
    ]
