# Generated by Django 5.1.4 on 2025-05-31 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0010_rename_porcentaje_ganacia_cotizacion_porcentaje_ganancia'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaDeMateriales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_general', models.TextField(blank=True, null=True)),
                ('cotizacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lista_materiales', to='cotizaciones.cotizacion')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleListaDeMateriales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('descripcion_material', models.TextField(blank=True, null=True)),
                ('cantidad', models.DecimalField(decimal_places=0, default=1.0, max_digits=10)),
                ('unidades', models.CharField(max_length=100)),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='cotizaciones.listademateriales')),
            ],
        ),
    ]
