# Generated by Django 5.1.4 on 2025-05-31 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0011_listademateriales_detallelistademateriales'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listademateriales',
            old_name='descripcion_general',
            new_name='descripcion_material',
        ),
        migrations.AddField(
            model_name='listademateriales',
            name='cantidad',
            field=models.DecimalField(decimal_places=0, default=1.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='listademateriales',
            name='item',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='listademateriales',
            name='unidades',
            field=models.CharField(default='Unidad', max_length=100),
        ),
        migrations.DeleteModel(
            name='DetalleListaDeMateriales',
        ),
    ]
