# Generated by Django 5.1.4 on 2025-05-31 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0012_rename_descripcion_general_listademateriales_descripcion_material_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listademateriales',
            name='cotizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lista_materiales', to='cotizaciones.cotizacion'),
        ),
    ]
