# Generated by Django 5.1.4 on 2025-05-31 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0013_alter_listademateriales_cotizacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listademateriales',
            options={'verbose_name': 'Lista de Materiales', 'verbose_name_plural': 'Listas de Materiales'},
        ),
    ]
