# Generated by Django 5.1.4 on 2025-05-31 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0014_alter_listademateriales_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listademateriales',
            name='item',
        ),
    ]
