# Generated by Django 5.1.4 on 2025-05-31 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0015_remove_listademateriales_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listademateriales',
            name='cantidad',
            field=models.DecimalField(blank=True, decimal_places=0, default=1.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='listademateriales',
            name='unidades',
            field=models.CharField(blank=True, default='Unidad', max_length=100),
        ),
    ]
