# Generated by Django 5.1.4 on 2025-05-31 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0016_alter_listademateriales_cantidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=0, default=0.0, max_digits=10),
        ),
    ]
