# Generated by Django 5.1.4 on 2025-05-31 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0017_alter_cotizacion_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
    ]
