# Generated by Django 5.1.4 on 2025-06-08 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0018_alter_cotizacion_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='correlativo',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
