# Generated by Django 5.1.4 on 2025-07-17 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0019_cotizacion_correlativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='condiciones_pago',
            field=models.CharField(choices=[('01', 'Contado'), ('02', 'Crédito'), ('05', 'Donación'), ('07', 'Otros')], default=None, max_length=20, verbose_name='Condición de Operación'),
        ),
    ]
