# Generated by Django 5.1.4 on 2025-07-17 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0020_alter_cotizacion_condiciones_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='condiciones_pago',
            field=models.CharField(choices=[('Contado', 'Contado'), ('Credito', 'Crédito'), ('Otros', 'Otros')], default=None, max_length=20, verbose_name='Condición de Operación'),
        ),
    ]
