# Generated by Django 5.1.4 on 2025-07-29 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0021_alter_cotizacion_condiciones_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='total_iva',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
    ]
