# Generated by Django 5.1.4 on 2025-09-02 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0022_cotizacion_total_iva'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotizacion',
            name='Cantidad',
        ),
    ]
