# Generated by Django 5.1.4 on 2025-09-12 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0023_remove_cotizacion_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallecotizacionproductos',
            name='unidades_cantidad',
            field=models.CharField(default='Unidad', max_length=50),
        ),
    ]
