# Generated by Django 5.1.4 on 2025-10-12 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0025_alter_cotizacion_porcentaje_administracion_and_more'),
        ('equipos_clientes', '0006_rename_orden_trabajo_historialmantenimiento_ordenes_trabajo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='equipo_cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipos_clientes.equipocliente'),
        ),
    ]
