# Generated by Django 5.1.4 on 2025-12-01 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0026_cotizacion_equipo_cliente'),
        ('equipos', '0017_rename_ubicación_equipo_ubicacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotizacion',
            name='equipo_cliente',
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='equipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipos.equipo'),
        ),
    ]
