# Generated by Django 5.1.4 on 2025-12-11 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0027_remove_cotizacion_equipo_cliente_cotizacion_equipo'),
        ('equipos', '0019_alter_historialtrabajos_fecha_registro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotizacion',
            name='equipo',
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='equipo',
            field=models.ManyToManyField(blank=True, null=True, to='equipos.equipo'),
        ),
    ]
