# Generated by Django 5.1.4 on 2025-12-11 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0028_remove_cotizacion_equipo_cotizacion_equipo'),
        ('equipos', '0019_alter_historialtrabajos_fecha_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='equipo',
            field=models.ManyToManyField(blank=True, to='equipos.equipo'),
        ),
    ]
