# Generated by Django 5.1.4 on 2025-12-29 20:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MensajeContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('mensaje', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mensaje de contacto',
                'verbose_name_plural': 'Mensajes de contacto',
            },
        ),
        migrations.CreateModel(
            name='Comunicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.CharField(default='cuerpo del mensaje', max_length=1000)),
                ('fecha_inicio', models.DateTimeField()),
                ('usuario_destino', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comunicaciones_recibidas', to=settings.AUTH_USER_MODEL)),
                ('usuario_remitente', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comunicaciones_enviadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comunicacion Interna',
                'verbose_name_plural': 'Comunicaciones internas',
            },
        ),
    ]
