# Generated by Django 5.1.4 on 2025-04-22 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comunicacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comunicacion',
            options={'verbose_name': 'Comunicacion', 'verbose_name_plural': 'Comunicaciones'},
        ),
    ]
