# Generated by Django 5.1.4 on 2025-04-27 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunicacion', '0004_alter_mensajecontacto_options_notificacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mensajecontacto',
            options={'verbose_name': 'Mensaje de contacto', 'verbose_name_plural': 'Mensajes de contacto'},
        ),
        migrations.AlterModelOptions(
            name='notificacion',
            options={},
        ),
        migrations.RenameField(
            model_name='notificacion',
            old_name='fecha_creacion',
            new_name='fecha',
        ),
        migrations.RenameField(
            model_name='notificacion',
            old_name='leido',
            new_name='leida',
        ),
        migrations.RemoveField(
            model_name='notificacion',
            name='usuario_destino',
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='mensaje',
            field=models.CharField(max_length=255),
        ),
    ]
