# Generated by Django 5.1.4 on 2025-04-28 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunicacion', '0005_alter_mensajecontacto_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificacion',
            options={'verbose_name': 'notificacion', 'verbose_name_plural': 'notificaciones'},
        ),
        migrations.RenameField(
            model_name='notificacion',
            old_name='fecha',
            new_name='fecha_creacion',
        ),
        migrations.RenameField(
            model_name='notificacion',
            old_name='leida',
            new_name='leido',
        ),
        migrations.AddField(
            model_name='notificacion',
            name='nivel',
            field=models.CharField(choices=[('info', 'Información'), ('warning', 'Advertencia'), ('error', 'Error')], default='info', max_length=20),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='titulo',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='mensaje',
            field=models.TextField(),
        ),
    ]
