# Generated by Django 5.1.4 on 2025-05-01 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comunicacion', '0006_alter_notificacion_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificacion',
            old_name='titulo',
            new_name='nombre',
        ),
    ]
