# Generated by Django 5.1.4 on 2025-05-01 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunicacion', '0007_rename_titulo_notificacion_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacion',
            name='nivel',
        ),
        migrations.AddField(
            model_name='notificacion',
            name='modulo_enlace',
            field=models.CharField(default='http://127.0.0.1:8000/admin/', max_length=500),
        ),
    ]
