# Generated by Django 5.1.4 on 2025-05-01 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunicacion', '0008_remove_notificacion_nivel_notificacion_modulo_enlace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='modulo_enlace',
            field=models.URLField(default='http://127.0.0.1:8000/admin/', max_length=500),
        ),
    ]
