# Generated by Django 5.1.4 on 2025-05-07 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comunicacion', '0009_alter_notificacion_modulo_enlace'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notificacion',
        ),
    ]
