# Generated by Django 5.1.4 on 2025-05-09 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunicacion', '0010_delete_notificacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comunicacion',
            options={'verbose_name': 'Comunicacion Interna', 'verbose_name_plural': 'Comunicaciones internas'},
        ),
        migrations.RemoveField(
            model_name='comunicacion',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='comunicacion',
            name='usuario',
        ),
        migrations.AddField(
            model_name='comunicacion',
            name='mensaje',
            field=models.CharField(default='cuerpo del mensaje', max_length=1000),
        ),
        migrations.AddField(
            model_name='comunicacion',
            name='usuario_destino',
            field=models.ForeignKey(blank=True, default=2, on_delete=django.db.models.deletion.CASCADE, related_name='comunicaciones_recibidas', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comunicacion',
            name='usuario_remitente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comunicaciones_enviadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
