# Generated by Django 5.1.4 on 2025-05-09 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunicacion', '0012_alter_comunicacion_usuario_destino'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunicacion',
            name='usuario_destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comunicaciones_recibidas', to=settings.AUTH_USER_MODEL),
        ),
    ]
