# Generated by Django 5.1.4 on 2025-02-07 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('equipos_clientes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Equipo',
            new_name='EquipoCliente',
        ),
        migrations.RemoveField(
            model_name='historialmantenimiento',
            name='equipo',
        ),
    ]
