# Generated by Django 5.1.4 on 2025-04-15 19:29

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos_clientes', '0002_rename_equipo_equipocliente_and_more'),
        ('proveedores', '0002_remove_proveedor_correo_remove_proveedor_creado_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipocliente',
            name='creado_en',
        ),
        migrations.RemoveField(
            model_name='historialmantenimiento',
            name='creado_en',
        ),
        migrations.RemoveField(
            model_name='historialmantenimiento',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='historialmantenimiento',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='historialmantenimiento',
            name='realizado_por',
        ),
        migrations.AddField(
            model_name='equipocliente',
            name='cantidad',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='equipocliente',
            name='categoria',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='equipocliente',
            name='estatus',
            field=models.CharField(default='funcionando', max_length=50),
        ),
        migrations.AddField(
            model_name='equipocliente',
            name='marca',
            field=models.CharField(default='Generico', max_length=100),
        ),
        migrations.AddField(
            model_name='historialmantenimiento',
            name='costo_mano_obra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='historialmantenimiento',
            name='descripcion_mant',
            field=models.CharField(default='breve descripción del mantenimiento realizado', max_length=100),
        ),
        migrations.AddField(
            model_name='historialmantenimiento',
            name='equipo_cliente',
            field=models.ForeignKey(default='especificar equipo', on_delete=django.db.models.deletion.CASCADE, related_name='historial_mantenimientos', to='equipos_clientes.equipocliente'),
        ),
        migrations.AddField(
            model_name='historialmantenimiento',
            name='fecha_mant',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha de Ultimo Mantenimiento'),
        ),
        migrations.AddField(
            model_name='historialmantenimiento',
            name='mot_mant',
            field=models.CharField(default='debe especificar el motivo del porque se realiza el mantenimiento', max_length=100),
        ),
        migrations.AddField(
            model_name='historialmantenimiento',
            name='notas',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='historialmantenimiento',
            name='proveedor_mantenimiento',
            field=models.ForeignKey(default='especificar el proveedor del mantenimiento', on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos_realizados_clientes', to='proveedores.proveedor'),
        ),
        migrations.AddField(
            model_name='historialmantenimiento',
            name='proveedor_repuestos',
            field=models.ForeignKey(default='especificar el proveedor de los repuestos', on_delete=django.db.models.deletion.CASCADE, related_name='repuestos_suministrados_clientes', to='proveedores.proveedor'),
        ),
        migrations.AddField(
            model_name='historialmantenimiento',
            name='proximo_mant',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha de Proximo Mantenimiento'),
        ),
        migrations.AddField(
            model_name='historialmantenimiento',
            name='repuestos',
            field=models.CharField(default='especificar los repuestos utilizados, nombre y cantidad', max_length=100),
        ),
        migrations.AddField(
            model_name='historialmantenimiento',
            name='tiempo_falla',
            field=models.DurationField(default=1),
        ),
        migrations.AddField(
            model_name='historialmantenimiento',
            name='tiempo_reparacion',
            field=models.DurationField(default=1),
        ),
        migrations.AddField(
            model_name='historialmantenimiento',
            name='usuario_asignado',
            field=models.CharField(default='admin', max_length=50),
        ),
        migrations.AlterField(
            model_name='equipocliente',
            name='descripcion',
            field=models.CharField(default='equipo de uso en empresa', max_length=100),
        ),
        migrations.AlterField(
            model_name='equipocliente',
            name='modelo',
            field=models.CharField(default='Modelo Generico', max_length=100),
        ),
        migrations.AlterField(
            model_name='equipocliente',
            name='serie',
            field=models.CharField(default='Serie Generica', max_length=100),
        ),
    ]
