# Generated by Django 5.1.4 on 2025-04-15 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos_clientes', '0004_alter_historialmantenimiento_equipo_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialmantenimiento',
            name='equipo_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_mantenimientos', to='equipos_clientes.equipocliente'),
        ),
    ]
