# Generated by Django 5.1.4 on 2025-12-29 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('categoria', models.CharField(max_length=100)),
                ('modelo', models.CharField(blank=True, max_length=100)),
                ('serie', models.CharField(blank=True, max_length=100)),
                ('codigo_interno', models.CharField(max_length=100, unique=True)),
                ('ficha_ingreso', models.DateField()),
                ('estado_sistema', models.CharField(choices=[('alta', 'De alta'), ('baja', 'De baja')], default='alta', max_length=5)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('observaciones', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Infraestructura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=150, null=True)),
                ('codigo_interno', models.CharField(max_length=50, unique=True)),
                ('encargado', models.CharField(blank=True, max_length=100, null=True)),
                ('caracteristicas', models.TextField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
