# Generated by Django 5.1.4 on 2025-12-29 20:59

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('equipos', '0001_initial'),
        ('productos', '0001_initial'),
        ('proveedores', '0001_initial'),
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factura_compra', models.CharField(blank=True, max_length=50, null=True)),
                ('correlativo', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('descripcion_general', models.TextField()),
                ('costo_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('costo_total_iva', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('fecha_compra', models.DateField()),
                ('fecha_aprobacion', models.DateField(blank=True, null=True)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedores.proveedor')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
            },
        ),
        migrations.CreateModel(
            name='DetalleProductos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('descripcion_producto', models.TextField(blank=True)),
                ('precio_unitario', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('unidades_cantidad', models.CharField(default='Unidad', max_length=50)),
                ('subtotal', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('cliente', models.ManyToManyField(blank=True, to='clientes.cliente')),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_productos', to='compras.compra')),
                ('equipo', models.ManyToManyField(blank=True, to='equipos.equipo')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.producto')),
            ],
            options={
                'verbose_name': 'Compra de Producto',
                'verbose_name_plural': 'Compras de Productos',
            },
        ),
        migrations.CreateModel(
            name='DetalleServicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('descripcion_servicio', models.TextField(blank=True)),
                ('unidades_cantidad', models.CharField(default='Unidad', max_length=50)),
                ('precio_unitario', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('cliente', models.ManyToManyField(blank=True, to='clientes.cliente')),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_servicios', to='compras.compra')),
                ('equipo', models.ManyToManyField(blank=True, to='equipos.equipo')),
                ('servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicios.servicio')),
            ],
            options={
                'verbose_name': 'Compra de Servicio',
                'verbose_name_plural': 'Compras de Servicios',
            },
        ),
    ]
