# Generated by Django 5.1.4 on 2026-02-27 00:02

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='descripcion_general',
            field=core.fields.RichTextSimpleField(),
        ),
        migrations.AlterField(
            model_name='detalleproductos',
            name='descripcion_producto',
            field=core.fields.RichTextSimpleField(blank=True),
        ),
        migrations.AlterField(
            model_name='detalleservicios',
            name='descripcion_servicio',
            field=core.fields.RichTextSimpleField(blank=True),
        ),
    ]
