# Generated by Django 5.1.4 on 2025-12-28 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0026_cliente_correlativo'),
        ('compras', '0003_alter_compra_options_remove_compra_cantidad_and_more'),
        ('equipos', '0020_remove_equipo_cantidad_equipo_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleproductos',
            name='cliente',
            field=models.ManyToManyField(blank=True, to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='detalleproductos',
            name='equipo',
            field=models.ManyToManyField(blank=True, to='equipos.equipo'),
        ),
        migrations.AddField(
            model_name='detalleservicios',
            name='cliente',
            field=models.ManyToManyField(blank=True, to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='detalleservicios',
            name='equipo',
            field=models.ManyToManyField(blank=True, to='equipos.equipo'),
        ),
    ]
