# Generated by Django 5.1.4 on 2025-12-28 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_detalleproductos_cliente_detalleproductos_equipo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalleproductos',
            old_name='descripcion',
            new_name='descripcion_producto',
        ),
        migrations.RenameField(
            model_name='detalleservicios',
            old_name='descripcion',
            new_name='descripcion_servicio',
        ),
    ]
