# Generated by Django 5.1.4 on 2025-12-28 20:58

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0005_rename_descripcion_detalleproductos_descripcion_producto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='costo_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='compra',
            name='costo_total_iva',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
