# Generated by Django 5.1.4 on 2025-12-28 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0006_alter_compra_costo_total_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compra',
            old_name='fecha_ingreso',
            new_name='fecha_compra',
        ),
    ]
