# Generated by Django 5.1.4 on 2025-12-28 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0007_rename_fecha_ingreso_compra_fecha_compra'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compra',
            old_name='descripcion',
            new_name='descripcion_general',
        ),
    ]
