# Generated by Django 5.1.4 on 2025-12-29 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=100)),
                ('correlativo', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('descripcion', models.CharField(default='descripcion de productos o servicios lo que proveen', max_length=100)),
                ('nombre_contacto', models.CharField(default='Nombre', max_length=100)),
                ('correo_electronico', models.CharField(default='ejemplo@dominio.com', max_length=100)),
                ('telefono', models.CharField(default='+503 7777-7777', max_length=15)),
                ('direccion', models.TextField()),
                ('nit_proveedor', models.CharField(default='0000000000', max_length=20)),
                ('nrc_proveedor', models.CharField(blank=True, max_length=20, null=True)),
                ('tipo_proveedor', models.CharField(choices=[('persona_natural', 'Persona Natural'), ('persona_juridica', 'Persona Jurídica')], default='persona_natural', max_length=20)),
                ('agente_retencion', models.BooleanField(default=False)),
                ('retencion_renta', models.BooleanField(default=False)),
                ('municipio', models.CharField(blank=True, max_length=100, null=True)),
                ('departamento', models.CharField(blank=True, max_length=100, null=True)),
                ('notas', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
    ]
