# Generated by Django 5.1.4 on 2025-02-06 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='creado_en',
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
