# Generated by Django 5.1.4 on 2026-02-27 00:02

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='descripcion',
            field=core.fields.RichTextSimpleField(default='descripcion de productos o servicios lo que proveen', max_length=100),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='direccion',
            field=core.fields.RichTextSimpleField(),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombre_contacto',
            field=core.fields.RichTextSimpleField(default='Nombre', max_length=100),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='notas',
            field=core.fields.RichTextSimpleField(blank=True, max_length=100),
        ),
    ]
