# Generated by Django 5.1.4 on 2025-04-22 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0002_remove_proveedor_correo_remove_proveedor_creado_en_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proveedor',
            options={'verbose_name': 'Proveedor', 'verbose_name_plural': 'Proveedores'},
        ),
    ]
