# Generated by Django 5.1.4 on 2026-03-27 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0002_alter_proveedor_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='nombre_contacto',
            field=models.CharField(default='Nombre', max_length=100),
        ),
    ]
