# Generated by Django 5.1.4 on 2025-04-22 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0003_alter_proveedor_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='descripcion',
            field=models.CharField(default='descripcion de productos o servicios lo que proveen', max_length=100),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='notas',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
