# Generated by Django 5.1.4 on 2025-04-22 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0004_proveedor_descripcion_proveedor_notas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='contacto',
        ),
        migrations.AddField(
            model_name='proveedor',
            name='correo_electronico',
            field=models.CharField(default='ejemplo@dominio.com', max_length=100),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='nombre_contacto',
            field=models.CharField(default='Nombre', max_length=100),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono',
            field=models.CharField(default='+503 7777-7777', max_length=15),
        ),
    ]
