# Generated by Django 5.1.4 on 2025-07-04 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0005_remove_proveedor_contacto_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proveedor',
            old_name='nombre',
            new_name='nombre_empresa',
        ),
        migrations.AddField(
            model_name='proveedor',
            name='departamento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='municipio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='nit',
            field=models.CharField(default='0000000000', max_length=20),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='nrc',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='tipo_proveedor',
            field=models.CharField(choices=[('persona_natural', 'Persona Natural'), ('persona_juridica', 'Persona Jurídica')], default='persona_natural', max_length=20),
        ),
    ]
