# Generated by Django 5.1.4 on 2025-07-04 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0006_rename_nombre_proveedor_nombre_empresa_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proveedor',
            old_name='nit',
            new_name='nit_proveedor',
        ),
        migrations.RenameField(
            model_name='proveedor',
            old_name='nrc',
            new_name='nrc_proveedor',
        ),
    ]
