# Generated by Django 5.1.4 on 2025-07-04 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0007_rename_nit_proveedor_nit_proveedor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='nit_proveedor',
            field=models.CharField(default='0000000000', max_length=20),
        ),
    ]
