# Generated by Django 5.1.4 on 2025-08-09 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0008_alter_proveedor_nit_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='agente_retencion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='retencion_renta',
            field=models.BooleanField(default=False),
        ),
    ]
