# Generated by Django 5.1.4 on 2025-09-12 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0009_proveedor_agente_retencion_proveedor_retencion_renta'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='correlativo',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
