# Generated by Django 5.1.4 on 2025-02-06 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='creado_en',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='nombre',
        ),
        migrations.AddField(
            model_name='equipo',
            name='cantidad',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='equipo',
            name='categoria',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='equipo',
            name='estatus',
            field=models.CharField(default='funcionando', max_length=50),
        ),
        migrations.AddField(
            model_name='equipo',
            name='marca',
            field=models.CharField(default='Generico', max_length=100),
        ),
        migrations.AddField(
            model_name='equipo',
            name='modelo',
            field=models.CharField(default='Modelo Generico', max_length=100),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='serie',
            field=models.CharField(default='Serie Generica', max_length=100),
        ),
        migrations.DeleteModel(
            name='HistorialMantenimiento',
        ),
    ]
