# Generated by Django 5.1.4 on 2025-02-06 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0002_remove_equipo_creado_en_remove_equipo_descripcion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='historial_mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='equipo',
            name='descripcion',
            field=models.CharField(default='equipo de uso en empresa', max_length=100),
        ),
        migrations.AddField(
            model_name='equipo',
            name='nombre',
            field=models.CharField(default='equipo_interno', max_length=100),
        ),
    ]
