# Generated by Django 5.1.4 on 2025-02-06 04:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0003_historial_mantenimiento_equipo_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historial_mantenimiento',
            name='fecha_proximo_mant',
            field=models.DateField(default=datetime.date.today, verbose_name='YYYY-MM-DD'),
        ),
        migrations.AddField(
            model_name='historial_mantenimiento',
            name='fecha_ultimo_mant',
            field=models.DateField(default=datetime.date.today, verbose_name='YYYY-MM-DD'),
        ),
        migrations.AddField(
            model_name='historial_mantenimiento',
            name='usuario_asignado',
            field=models.CharField(default='admin', max_length=50),
        ),
    ]
