# Generated by Django 5.1.4 on 2025-02-06 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0004_historial_mantenimiento_fecha_proximo_mant_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='historial_mantenimiento',
            new_name='HistorialMantenimiento',
        ),
    ]
