# Generated by Django 5.1.4 on 2025-02-06 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0005_rename_historial_mantenimiento_historialmantenimiento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historialmantenimiento',
            old_name='fecha_proximo_mant',
            new_name='ProximoMant',
        ),
        migrations.RenameField(
            model_name='historialmantenimiento',
            old_name='fecha_ultimo_mant',
            new_name='UltimoMant',
        ),
        migrations.RenameField(
            model_name='historialmantenimiento',
            old_name='usuario_asignado',
            new_name='UsuarioAsignado',
        ),
    ]
