# Generated by Django 5.1.4 on 2025-02-06 04:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0006_rename_fecha_proximo_mant_historialmantenimiento_proximomant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialmantenimiento',
            name='ProximoMant',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha de Proximo Mantenimiento'),
        ),
        migrations.AlterField(
            model_name='historialmantenimiento',
            name='UltimoMant',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha de Ultimo Mantenimiento'),
        ),
    ]
