# Generated by Django 5.1.4 on 2025-04-15 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0007_alter_historialmantenimiento_proximomant_and_more'),
        ('proveedores', '0002_remove_proveedor_correo_remove_proveedor_creado_en_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historialmantenimiento',
            old_name='UltimoMant',
            new_name='fecha_mant',
        ),
        migrations.RenameField(
            model_name='historialmantenimiento',
            old_name='ProximoMant',
            new_name='proximo_mant',
        ),
        migrations.RenameField(
            model_name='historialmantenimiento',
            old_name='UsuarioAsignado',
            new_name='usuario_asignado',
        ),
        migrations.AddField(
            model_name='historialmantenimiento',
            name='costo_mano_obra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='historialmantenimiento',
            name='descripcion_mant',
            field=models.CharField(default='breve descripción del mantenimiento realizado', max_length=100),
        ),
        migrations.AddField(
            model_name='historialmantenimiento',
            name='equipo',
            field=models.ForeignKey(default='especificar equipo', on_delete=django.db.models.deletion.CASCADE, related_name='historial_mantenimientos', to='equipos.equipo'),
        ),
        migrations.AddField(
            model_name='historialmantenimiento',
            name='mot_mant',
            field=models.CharField(default='debe especificar el motivo del porque se realiza el mantenimiento', max_length=100),
        ),
        migrations.AddField(
            model_name='historialmantenimiento',
            name='notas',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='historialmantenimiento',
            name='proveedor_mantenimiento',
            field=models.ForeignKey(default='especificar el proveedor del mantenimiento', on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos_realizados_equipos', to='proveedores.proveedor'),
        ),
        migrations.AddField(
            model_name='historialmantenimiento',
            name='proveedor_repuestos',
            field=models.ForeignKey(default='especificar el proveedor de los repuestos', on_delete=django.db.models.deletion.CASCADE, related_name='repuestos_suministrados_equipos', to='proveedores.proveedor'),
        ),
        migrations.AddField(
            model_name='historialmantenimiento',
            name='repuestos',
            field=models.CharField(default='especificar los repuestos utilizados, nombre y cantidad', max_length=100),
        ),
        migrations.AddField(
            model_name='historialmantenimiento',
            name='tiempo_falla',
            field=models.DurationField(default=1),
        ),
        migrations.AddField(
            model_name='historialmantenimiento',
            name='tiempo_reparacion',
            field=models.DurationField(default=1),
        ),
    ]
