# Generated by Django 5.1.4 on 2025-04-15 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0008_rename_ultimomant_historialmantenimiento_fecha_mant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialmantenimiento',
            name='equipo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='historial_mantenimientos', to='equipos.equipo'),
        ),
    ]
