# Generated by Django 5.1.4 on 2025-04-15 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0009_alter_historialmantenimiento_equipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialmantenimiento',
            name='equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_mantenimientos', to='equipos.equipo'),
        ),
    ]
