# Generated by Django 5.1.4 on 2025-02-06 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=500)),
                ('actividad', models.CharField(max_length=500)),
                ('motivo_actividad', models.CharField(max_length=500)),
                ('procedimiento', models.CharField(max_length=50)),
                ('formulario', models.CharField(max_length=50)),
                ('frecuencia', models.CharField(max_length=50)),
                ('especialista', models.CharField(max_length=100)),
                ('proveedores', models.CharField(max_length=500)),
                ('ultima_fecha', models.DateField()),
                ('proxima_fecha', models.DateField()),
                ('tiempo_realizacion', models.DateField()),
                ('notas', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipos.equipo')),
            ],
        ),
    ]
