# Generated by Django 5.1.4 on 2025-04-14 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentacion', '0001_initial'),
        ('planes_mantenimiento', '0001_initial'),
        ('proveedores', '0002_remove_proveedor_correo_remove_proveedor_creado_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planmantenimiento',
            name='actividad',
        ),
        migrations.RemoveField(
            model_name='planmantenimiento',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='planmantenimiento',
            name='creado_en',
        ),
        migrations.RemoveField(
            model_name='planmantenimiento',
            name='especialista',
        ),
        migrations.RemoveField(
            model_name='planmantenimiento',
            name='formulario',
        ),
        migrations.RemoveField(
            model_name='planmantenimiento',
            name='frecuencia',
        ),
        migrations.RemoveField(
            model_name='planmantenimiento',
            name='motivo_actividad',
        ),
        migrations.RemoveField(
            model_name='planmantenimiento',
            name='notas',
        ),
        migrations.RemoveField(
            model_name='planmantenimiento',
            name='procedimiento',
        ),
        migrations.RemoveField(
            model_name='planmantenimiento',
            name='proveedores',
        ),
        migrations.RemoveField(
            model_name='planmantenimiento',
            name='proxima_fecha',
        ),
        migrations.RemoveField(
            model_name='planmantenimiento',
            name='tiempo_realizacion',
        ),
        migrations.RemoveField(
            model_name='planmantenimiento',
            name='ultima_fecha',
        ),
        migrations.AddField(
            model_name='planmantenimiento',
            name='descripcion',
            field=models.TextField(default='Plan de mantenimiento personalizado'),
        ),
        migrations.CreateModel(
            name='DetallePlanMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad', models.CharField(max_length=500)),
                ('motivo_actividad', models.CharField(max_length=500)),
                ('frecuencia', models.CharField(max_length=100)),
                ('especialidad', models.CharField(max_length=100)),
                ('especialista', models.CharField(max_length=100)),
                ('ultima_fecha', models.DateField()),
                ('proxima_fecha', models.DateField()),
                ('tiempo_realizacion', models.DateField()),
                ('notas', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('consideraciones', models.TextField(blank=True, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='planes_mantenimiento.planmantenimiento')),
                ('procedimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documentacion.documentacion')),
                ('proveedores', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedores.proveedor')),
            ],
        ),
    ]
