# Generated by Django 5.1.4 on 2025-04-14 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planes_mantenimiento', '0002_remove_planmantenimiento_actividad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleplanmantenimiento',
            name='consideraciones',
        ),
    ]
