# Generated by Django 5.1.4 on 2025-04-14 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes_mantenimiento', '0003_remove_detalleplanmantenimiento_consideraciones'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalleplanmantenimiento',
            old_name='proxima_fecha',
            new_name='tiempo_realizacion_estimado',
        ),
        migrations.RemoveField(
            model_name='detalleplanmantenimiento',
            name='tiempo_realizacion',
        ),
        migrations.RemoveField(
            model_name='detalleplanmantenimiento',
            name='ultima_fecha',
        ),
        migrations.AddField(
            model_name='detalleplanmantenimiento',
            name='cantidad_personas',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='detalleplanmantenimiento',
            name='herramientas',
            field=models.CharField(default='caja de herramientas', max_length=500),
        ),
    ]
