# Generated by Django 5.1.4 on 2025-04-14 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes_mantenimiento', '0005_alter_detalleplanmantenimiento_tiempo_realizacion_estimado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleplanmantenimiento',
            name='tiempo_realizacion_estimado',
            field=models.DurationField(),
        ),
    ]
