# Generated by Django 5.1.4 on 2025-06-22 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes_mantenimiento', '0006_alter_detalleplanmantenimiento_tiempo_realizacion_estimado'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleplanmantenimiento',
            name='hora_realizacion_estimada',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
